      SUBROUTINE EXORG
      IMPLICIT NONE
C----------
C  **EXORG--BASE   DATE OF LAST REVISION:  01/11/2012
C----------
C
C     EXTRA EXTERNAL REFERENCES FOR ORGANON EXTENSION CALLS
C     THIS FILE IS COMPILED AND LINKED INTO THE FVS PROGRAM
C     WHEN THE ORGANON EXTENSION IS *NOT* INCLUDED IN THE 
C     FVS PROGRAM.
C
COMMONS
C
      INCLUDE 'PRGPRM.F77'
C
COMMONS
C
      LOGICAL DEBUG,LKECHO
      INTEGER KEY,IRECNT
      CHARACTER*8 KEYWRD,NOORG 
C
      DATA NOORG/'*NO ORG'/
      
      ENTRY ORINIT
      RETURN
C     ENTRY ORIN  (DEBUG,LKECHO)
      CALL ERRGRO (.TRUE.,11)
      RETURN

      END
