      SUBROUTINE PTBAL
      IMPLICIT NONE
C----------
C LS $Id$
C----------
C     DUMMY VERSION FOR VARIANTS THAT DON'T REQUIRE BASAL AREA IN LARGER
C     TREES ON A POINT-BY-POINT BASIS.
C----------
      RETURN
      END
