      SUBROUTINE FINDAG(I,ISPC,D1,D2,H,SITAGE,SITHT,AGMAX,HTMAX1,HTMAX2,
     &                  DEBUG)
      IMPLICIT NONE
C----------
C IE $Id: findag.f 0000 2018-02-14 00:00:00Z gedixon $
C----------
C  THIS ROUTINE SET EFFECTIVE TREE AGE BASED ON INPUT VARIABLE(S)
C  SUCH AS TREE HEIGHT.  IN IE, AGE IS CALCULATED FOR AS,MM,AND PB
C  CALLED FROM **CRATET
C  CALLED FROM **COMCUP
C
C  COMMONS
C
      INCLUDE 'PRGPRM.F77'
C
      INCLUDE 'CONTRL.F77'
C
C  COMMONS
C----------
      LOGICAL DEBUG
      INTEGER I,ISPC
      REAL D1,D2,H,SITAGE,SITHT,AGMAX,HTMAX1,HTMAX2
      REAL RDANUW
      INTEGER IDANUW
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
      RDANUW = AGMAX
      RDANUW = D1
      RDANUW = D2
      RDANUW = HTMAX1
      RDANUW = HTMAX2
      IDANUW = ISPC
C
C---------
C  COMPUTE AGE FOR ASPEN. THIS EQUATION IS ALSO USED FOR MM AND PB.
C  EQUATION FORMULATED BY
C  WAYNE SHEPPERD, ROCKY MTN FOREST EXP STATION, FT COLLINS, CO.
C----------
      SITAGE = (H*2.54*12.0/26.9825)**(1.0/1.1752)
C
      IF(DEBUG)WRITE(JOSTND,50)I,SITAGE,SITHT
   50 FORMAT(' LEAVING SUBROUTINE FINDAG I,SITAGE,SITHT =',I5,2F10.3)
C
      RETURN
      END
