      SUBROUTINE DUNN (SS)
      IMPLICIT NONE
C----------
C  **DUNN--NI   DATE OF LAST REVISION:  04/09/08
C----------
C
C     THIS SUBROUTINE PROCESSES THE DUNNING SITE CODE INFORMATION
C     ENTERED ON THE SITECODE KEYWORD. FOR INLAND EMPIRE VARIANT
C     THIS SUBROUTINE IS A DUMMY.
C
COMMONS
C
C
      REAL SS
      RETURN
      END
