      SUBROUTINE EXPPNB
      IMPLICIT NONE
C----------
C  **EXPPNB-NI  DATE OF LAST REVISION:  04/09/08
C----------
C
C     VARIANT DEPENDENT EXTERNAL REFERENCES FOR THE
C     PARALLEL PROCESSING EXTENSION
C
C
C     CALLED TO COMPUTE THE DDS MODIFIER THAT ACCOUNTS FOR THE DENSITY
C     OF NEIGHBORING STANDS (CALLED FROM DGF).
C
      REAL BDBL,BBAL,BCCF,DBH,CCFO,BALO,XPPDDS,XPPMLT
      ENTRY PPDGF (XPPDDS,BALO,CCFO,DBH,BCCF,BBAL,BDBL)
      RETURN
C
C     CALLED TO COMPUTE THE REGENT MULTIPLIER THAT ACCOUNTS FOR
C     THE DENSITY OF NEIGHBORING STANDS (CALLED FROM REGENT).
C
      ENTRY PPREGT (XPPMLT,CCFO,BALO,BCCF,BBAL)
      RETURN
      END
