      SUBROUTINE FINDAG(I,ISPC,D1,D2,H,SITAGE,SITHT,AGMAX,HTMAX1,HTMAX2,
     &                  DEBUG)
      IMPLICIT NONE
C----------
C  **FINDAG--NI  DATE OF LAST REVISION:  01/14/11
C----------
C  IN THE NI VARIANT, FINDAG IS A DUMMY ROUTINE THAT RETURNS WITHOUT
C  EXECUTING ANY COMPUTATIONS.  IN OTHER VARIANTS THIS ROUTINE
C  MAY SET EFFECTIVE TREE AGE BASED ON INPUT VARIABLE(S)
C  SUCH AS TREE HEIGHT.
C  CALLED FROM **COMCUP
C  CALLED FROM **CRATET
C
C  COMMONS
C
      INCLUDE 'PRGPRM.F77'
C
      INCLUDE 'CONTRL.F77'
C
C----------
      LOGICAL DEBUG
      INTEGER I,ISPC
      REAL D1,D2,H,SITAGE,SITHT,AGMAX,HTMAX1,HTMAX2
C
      IF(DEBUG)WRITE(JOSTND,50)I,SITAGE,SITHT
   50 FORMAT(' LEAVING SUBROUTINE FINDAG  I,SITAGE,SITHT =',I5,2F10.3)
C
      RETURN
      END
C**END OF CODE SEGMENT
