      SUBROUTINE DFBDRV
      IMPLICIT NONE
C----------
C  **DFBDRV  DATE OF LAST REVISION:  06/30/10
C----------
C
C  THIS SUBROUTINE CALLS THE DFB MODEL SUBROUTINES THAT CAUSE THE
C  DOUGLAS-FIR MORTALITY.
C
C  CALLED BY :
C     GRADD   [PROGNOSIS]
C
C  CALLS :
C     DFBDBH  (SUBROUTINE)   [DFB]
C     DFBMOD  (SUBROUTINE)   [DFB]
C     DFBMRT  (SUBROUTINE)   [DFB]
C
C  COMMON BLOCK VARIABLES USED :
C     DEBUIN (DFBCOM)  INPUT
C     JODFB  (DFBCOM)  INPUT
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'DFBCOM.F77'
C
C
COMMONS
C
      IF (DEBUIN) WRITE (JODFB,*) ' ** ENTERING SUBROUTINE DFBDRV'
 
C
C     INITIALIZE START VALUES.
C
      CALL DFBDBH

C
C     CALCULATE THE NUMBER OF TREES TO KILL.
C
      CALL DFBMOD

C
C     PASS THE MORTALITY BACK TO PROGNOSIS.
C
      CALL DFBMRT

      IF (DEBUIN) WRITE (JODFB,*) ' ** LEAVING SUBROUTINE DFBDRV'

      RETURN
      END
