      SUBROUTINE FORMCL(ISPC,IFOR,D,FC)
      IMPLICIT NONE
C----------
C  **FORMCL--SN     DATE OF LAST REVISION:  06/05/08
C----------
C
      INTEGER IFOR,ISPC
      REAL FC,D
C
C  THIS IS A DUMMY ROUTINE TO RETURN FORMCLASS 80 TO CALLING ROUTINE
C
      FC= 80
C
      RETURN
      END
