      SUBROUTINE VARPUT (WK3,IPNT,ILIMIT,REALS,LOGICS,INTS)
      IMPLICIT NONE
C----------
C  $Id
C----------
C
C     WRITE THE VARIANT SPECIFIC VARIABLES. EXCEPT FOR 2 VARIABLES FROM ESHAP.F77 (BC-ESTAB),
C     ALL VARIABLES ARE FROM BCPLOT.F77
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
      INCLUDE 'BCPLOT.F77'
      INCLUDE 'ESHAP.F77'
C
C
COMMONS
C
C     NOTE: THE ACTUAL STORAGE LIMIT FOR INTS, LOGICS, AND REALS
C     IS MAXTRE (SEE PRGPRM).
C
      INTEGER MXL,MXR,MXI,IRECLN
      PARAMETER (MXR=2,MXL=3,MXI=1,IRECLN=1024)

      INTEGER ILIMIT,IPNT,I,J,K
      LOGICAL LOGICS(MXL), LC(MAXSP)
      INTEGER INTS(MXI)
      REAL REALS(MXR),     RC(MAXSP)
      REAL WK3(MAXTRE)

C     PUT THE INTEGER SCALARS
!     CALL IFWRIT (WK3, IPNT, ILIMIT, INTS, MXI, 2) ! NONE

C     PUT THE INTEGER ARRAYS
      CALL IFWRIT (WK3, IPNT, ILIMIT, JDST, 3, 2)

C     PUT THE LOGICAL SCALARS
      LOGICS(1) = LV2ATV
      LOGICS(2) = LV2HTCP
      LOGICS(3) = LV2HDR
      CALL LFWRIT (WK3, IPNT, ILIMIT, LOGICS, MXL, 2)

C     PUT THE LOGICAL ARRAYS
      CALL LFWRIT (WK3, IPNT, ILIMIT, LLTDGOK, MAXSP, 2)
      CALL LFWRIT (WK3, IPNT, ILIMIT, LMHTDUB, MAXSP, 2)

C     PUT THE LOGICAL ARRAYS FOR MORT, LTH & STG STRUCTURES
      LC = MORT%FIT
      CALL LFWRIT (WK3,IPNT,ILIMIT, LC, MAXSP, 2)
      LC = LTH%FIT
      CALL LFWRIT (WK3,IPNT,ILIMIT, LC, MAXSP, 2)
      LC = STG%FIT
      CALL LFWRIT (WK3,IPNT,ILIMIT, LC, MAXSP, 2)

C     PUT THE REAL SCALARS
      REALS(1) = SEISHT
      REALS(2) = ZBRSH
      CALL BFWRIT (WK3, IPNT, ILIMIT, REALS, MXR, 2)

C     PUT THE REAL ARRAYS
      DO I=1,MRT_PY
         DO J=1,MRT_BA_UB
            DO K=1,MRT_DBH_UB
               CALL BFWRIT (WK3,IPNT,ILIMIT,TMRT(I,J,K), 1, 2)
            ENDDO
         ENDDO
      ENDDO
      CALL BFWRIT (WK3,IPNT,ILIMIT,DGLD1,    MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,DGBAL1,   MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,DGCR1,    MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,DGDBAL1,  MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,DGDBAL2,  MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,DGCCF1,   MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,DGDSQ1,   MAXSP,  2)

      CALL BFWRIT (WK3,IPNT,ILIMIT,CRHTDBH,  MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,CRHT,     MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,CRDBH2,   MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,CRBAL,    MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,CRLNCCF,  MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,CRSD,     MAXSP,  2)

      CALL BFWRIT (WK3,IPNT,ILIMIT,V2SEICOR, MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,SEICON,   MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,XHT1B,    MAXSP,  2)
      CALL BFWRIT (WK3,IPNT,ILIMIT,XHT2B,    MAXSP,  2)

C     PUT THE REAL ARRAYS FOR MORT STRUCTURE
      RC = MORT%CON
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = MORT%INVDBH
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = MORT%DBH
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = MORT%DBHSQ
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = MORT%RDBH
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = MORT%BAL
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = MORT%SQRTBA
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = MORT%SPH
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)

C     PUT THE REAL ARRAYS FOR LTH STRUCTURE
      RC = LTH%MLT
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = LTH%A1
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = LTH%B1
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = LTH%B2
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = LTH%SI
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = LTH%B3
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = LTH%C
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = LTH%CN
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = LTH%CNSI
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = LTH%DG
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = LTH%DG2
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = LTH%DBH1
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = LTH%DBH2
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = LTH%HT2
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)

C     PUT THE REAL ARRAYS FOR STG STRUCTURE
      RC = STG%CON
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = STG%LNHT
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = STG%HT
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = STG%CCF
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = STG%BAL
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = STG%EXPMLT
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = STG%HCCFL
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = STG%CCFSL
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      RC = STG%SD
      CALL BFWRIT (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)

      RETURN
      END

      SUBROUTINE VARCHPUT (CBUFF, IPNT, LNCBUF)
      IMPLICIT NONE
C
COMMONS
C
      INCLUDE 'PRGPRM.F77'
      INCLUDE 'BCPLOT.F77'
C
      INTEGER LNCBUF, IPNT
      CHARACTER CBUFF(LNCBUF), CT
      INTEGER I

C     PUT THE CHARACTER DATA FOR BEC STRUCTURE
      DO I=1,3
         CT = BEC%Region(I:I)
         CALL CHWRIT (CBUFF,IPNT,LNCBUF,CT,2)
      ENDDO
      DO I=1,4
         CT = BEC%Zone(I:I)
         CALL CHWRIT (CBUFF,IPNT,LNCBUF,CT,2)
      ENDDO
      DO I=1,3
         CT = BEC%SubZone(I:I)
         CALL CHWRIT (CBUFF,IPNT,LNCBUF,CT,2)
      ENDDO
      DO I=1,5
         CT = BEC%Series(I:I)
         CALL CHWRIT (CBUFF,IPNT,LNCBUF,CT,2)
      ENDDO
      DO I=1,7
         CT = BEC%FullName(I:I)
         CALL CHWRIT (CBUFF,IPNT,LNCBUF,CT,2)
      ENDDO
      DO I=1,15
         CT = BEC%PrettyName(I:I)
         CALL CHWRIT (CBUFF,IPNT,LNCBUF,CT,2)
      ENDDO

C     PUT THE CHARACTER DATA FOR MORT STRUCTURE
      DO I=1,15
         CT = MORT%PrettyName(I:I)
         CALL CHWRIT (CBUFF,IPNT,LNCBUF,CT,2)
      ENDDO

C     PUT THE CHARACTER DATA FOR LTH STRUCTURE
      DO I=1,15
         CT = LTH%PrettyName(I:I)
         CALL CHWRIT (CBUFF,IPNT,LNCBUF,CT,2)
      ENDDO

C     PUT THE CHARACTER DATA FOR STG STRUCTURE
      DO I=1,15
         CT = STG%PrettyName(I:I)
         CALL CHWRIT (CBUFF,IPNT,LNCBUF,CT,2)
      ENDDO

      RETURN
      END

