      SUBROUTINE VOLUMELIB(REGN,FORST,VOLEQ,MTOPP,MTOPS,STUMP,DBHOB,
     &    DRCOB,HTTYPE,HTTOT,HTLOG,HT1PRD,HT2PRD,UPSHT1,UPSHT2,UPSD1,
     &    UPSD2,HTREF,AVGZ1,AVGZ2,FCLASS,DBTBH,BTR,I3,I7,I11,I20,I21,
     &    VOL11,LOGVOL,LOGDIA,LOGLEN,BOLHT,TLOGS,NOLOGP,NOLOGS,CUTFLG,
     &    BFPFLG,CUPFLG,CDPFLG,CUSFLG,CDSFLG,CONSPEC,PROD,HTTFLL,LIVE,
     &    BA,SI,CTYPE,ERRFLAG)

!== last modified  02-26-2004     Main call into volume dll
!	VOLUMELIB      - subroutine 
!
      IMPLICIT NONE

  ! Expose subroutine VOLUMELIB to users of this DLL
  !
!  !DEC$ ATTRIBUTES DLLEXPORT::VOLUMELIB

!
!   THERE ARE CALLS TO THE FOLLOWING SUBROUTINES
!     PROFILE - EXTERNAL 
!     DVE     - EXTERNAL
!     R4VOL  - EXTERNAL 
!     R6VOL  - EXTERNAL 
!     BLMVOL - EXTERNAL
!     R8VOL  - EXTERNAL
!     R10VOL - EXTERNAL
!     R12VOL - EXTERNAL 
!*****DECLARE VARIABLES

      CHARACTER*(*) HTTYPE,LIVE,CTYPE
      CHARACTER*(*) FORST,PROD
      character*(*) conspec
      CHARACTER*(*) VOLEQ
      CHARACTER*3 MDL
      CHARACTER*2 DIST
      INTEGER IDIST
!     MERCH VARIABLES 
      INTEGER REGN,HTTFLL,BA,SI
      REAL STUMP,MTOPP,MTOPS,THT1
      INTEGER CUTFLG,BFPFLG,CUPFLG,CDPFLG,CUSFLG,CDSFLG,ERRFLAG,SPFLG
         
!     TREE VARIABLES
      REAL HTTOT,HT1PRD,HT2PRD 
      REAL DBHOB,DRCOB,DBTBH,BTR
      INTEGER FCLASS,HTLOG

!   	3RD POINT VARIABLES
      REAL UPSD1,UPSD2,UPSHT1,UPSHT2,AVGZ1,AVGZ2    
      INTEGER HTREF

!     OUTPUTS
      REAL NOLOGP,NOLOGS
      INTEGER TLOGS

!     ARRAYS
      INTEGER I11,I15,I21,I20,I7,I3,I,J
      REAL VOL11(I11),LOGVOL(I7,I20)
      REAL LOGDIA(I21,I3),LOGLEN(I20),BOLHT(I21)
      REAL VOL(15)
    
!---------------------------------------------------------------------
   
      CALL VOLINIT(REGN,FORST,VOLEQ,MTOPP,MTOPS,STUMP,DBHOB,
     +    DRCOB,HTTYPE,HTTOT,HTLOG,HT1PRD,HT2PRD,UPSHT1,UPSHT2,UPSD1,
     +    UPSD2,HTREF,AVGZ1,AVGZ2,FCLASS,DBTBH,BTR,I3,I7,I15,I20,I21,
     +    VOL,LOGVOL,LOGDIA,LOGLEN,BOLHT,TLOGS,NOLOGP,NOLOGS,CUTFLG,
     +    BFPFLG,CUPFLG,CDPFLG,SPFLG,CONSPEC,PROD,HTTFLL,LIVE,
     +    BA,SI,CTYPE,ERRFLAG,IDIST)
 4000 RETURN
      END SUBROUTINE VOLUMELIB