      SUBROUTINE FORKOD
      IMPLICIT NONE
C----------
C  **FORKOD--CS DATE OF LAST REVISION:  05/19/08
C----------
C
C     TRANSLATES FOREST CODE INTO A SUBSCRIPT, IFOR, AND IF
C     KODFOR IS ZERO, THE ROUTINE RETURNS THE DEFAULT CODE.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'PLOT.F77'
C
C
      INCLUDE 'CONTRL.F77'
C
C
COMMONS
C----------
C  NATIONAL FORESTS:
C  905 = MARK TWAIN
C  908 = SHAWNEE
C  912 = HOOSIER
C  911 = OLD WAYNE-HOOSIER COMBINED CODE (MAP TO HOOSIER)
C----------
      INTEGER JFOR(4),KFOR(4),NUMFOR,I
      DATA JFOR/905,908,912,911/
      DATA NUMFOR/4/
      DATA KFOR/1,1,1,1/
C
      IF (KODFOR .EQ. 0) GOTO 30
      DO 10 I=1,NUMFOR
      IF (KODFOR .EQ. JFOR(I)) GOTO 20
   10 CONTINUE
      CALL ERRGRO (.TRUE.,3)
      WRITE(JOSTND,11) JFOR(IFOR)
   11 FORMAT(T13,'FOREST CODE USED FOR THIS PROJECTION IS',I4)
      GOTO 30
   20 CONTINUE
      IF(I .EQ. 4)THEN
        WRITE(JOSTND,21)
   21   FORMAT(T13,'WAYNE-HOOSIER NF (911) BEING MAPPED TO HOOSIER ',
     &  '(912) FOR FURTHER PROCESSING.')
        I=3
      ENDIF
      IFOR=I
      IGL=KFOR(I)
   30 CONTINUE
      KODFOR=JFOR(IFOR)
C----------
C  SET DEFAULT TLAT, TLONG, AND ELEVATION VALUES, BY FOREST
C----------
      SELECT CASE(KODFOR)
      CASE(905)
        IF(TLAT.EQ.0) TLAT=37.95
        IF(TLONG.EQ.0)TLONG=91.77
        IF(ELEV.EQ.0) ELEV=10.
      CASE(908)
        IF(TLAT.EQ.0) TLAT=37.74
        IF(TLONG.EQ.0)TLONG=88.54
        IF(ELEV.EQ.0) ELEV=4.
      CASE(911,912)
        IF(TLAT.EQ.0) TLAT=38.86
        IF(TLONG.EQ.0)TLONG=86.49
        IF(ELEV.EQ.0) ELEV=6.
      END SELECT
      RETURN
      END
