
#all : ont01
all : ont01 ont02


ont01 : 
#	@echo Test ont01, basic functionality 
#	-../../bin/FVSon --keywordfile=ont01.key
#	grep -v "\-999" ont01.sum      > ont01.tmp
#	grep -v "\-999" ont01.sum.save > ont01.tmp.save
#	-diff -w ont01.tmp ont01.tmp.save
#	rm ont01.tmp ont01.tmp.save
#	@echo Test ont01 ended
	
ont02 : 
#	@echo Test ont02, stop/restart
#	-../../bin/FVSon --keywordfile=ont01.key --stoppoint=2,2020,ont.stop
#	-../../bin/FVSon --restart=ont.stop
#	grep -v "\-999" ont01.sum      > ont01.tmp
#	grep -v "\-999" ont01.sum.save > ont01.tmp.save
#	-diff -w ont01.tmp ont01.tmp.save
#	rm ont01.tmp ont01.tmp.save
#	@echo Test ont02 ended

	
	
