      SUBROUTINE EXDFB
      IMPLICIT NONE
C----------
C BASE $Id$
C----------
C
C     EXTRA EXTERNAL REFERENCES FOR DFB CALLS
C
      LOGICAL L,LNOTBK,LKECHO
      CHARACTER*8 KEYWRD,NODFB
      REAL ARRAY(7)
      DIMENSION LNOTBK(7)
      INTEGER ICODES(6),II,KEY
      DATA NODFB/'*NO DFB'/

      ENTRY DFBINT
      RETURN
      ENTRY DFBIN (KEYWRD,ARRAY,LNOTBK,LKECHO)
      CALL ERRGRO (.TRUE.,11)
      RETURN
      ENTRY DFBDAM (II,ICODES)
      RETURN
      ENTRY DFBSCH
      RETURN
      ENTRY DFBDRV
      RETURN
      ENTRY DFBGO (L)
      L = .FALSE.
      RETURN
      ENTRY DFBOUT
      RETURN
      ENTRY DFBINV
      RETURN
      ENTRY DFBWIN (L)
      RETURN
      ENTRY DFBKEY (KEY,KEYWRD)
      KEYWRD=NODFB
      RETURN
      END
