      SUBROUTINE EXFERT
      IMPLICIT NONE
C----------
C  **EXFERT DATE OF LAST REVISION:  07/23/08
C----------
C
C     EXTRA EXTERNAL REFERENCES FOR FERTILIZER CALLS
C
      LOGICAL LNOTBK(7),LKECHO
      REAL ARRAY(7)
      INTEGER IRECNT,JOSTND
      CHARACTER*8 KEYWRD
      CHARACTER*10 KARD(7)
C
      ENTRY FFIN (JOSTND,IRECNT,KEYWRD,ARRAY,LNOTBK,KARD,LKECHO)
      CALL ERRGRO (.TRUE.,11)
      RETURN
      ENTRY FFERT
      RETURN
      END
