      SUBROUTINE EXFIRE
      IMPLICIT NONE
C----------
C  **EXFIRE--BASE DATE OF LAST REVISION:  06/29/10
C----------
C
C     EXTRA EXTERNAL REFERENCES FOR THE FIRE MODEL.
C
      CHARACTER*4 NSP(1,*)
      CHARACTER*7 CH7
      CHARACTER*8 KEYWRD,NOFM
      CHARACTER*13 CFOTO
      INTEGER     I,I1,I2,I3,I4,J,J1,J2,K,IYR,I5
      INTEGER     IVAC,IREC,ISPC,IC,ITFN,NCLAS,NR,NC,KEY
      REAL        XMXVOL(*),CTCRWN(*),SSNG(*),DSNG(*),TKCRWN(*),FLNY(*)
      REAL        D,H,P,X,WEIGHT,XXX(*),X1,X2,X3,X4,X5,X6
      REAL        CRBSHT,CRBLKD,CANCOV,POKL,POVK
      REAL        KFMS(*),FMWTS(*),FMLOADS(*),AX(*)
      LOGICAL     LACTV,LDEB,LFM,LKECHO,L1,L2
C
      DATA NOFM/'*NO FIRE'/
C
      ENTRY FMIN (I1,NSP,LKECHO)
      CALL ERRGRO (.TRUE.,11)
      RETURN
      ENTRY FMINIT
      RETURN
      ENTRY FMCMPR (NCLAS)
      RETURN
      ENTRY FMTDEL (IVAC,IREC)
      RETURN
      ENTRY FMSDIT
      RETURN
      ENTRY FMMAIN
      RETURN
      ENTRY FMKILL(I)
      RETURN
      ENTRY FMSSEE (I,ISPC,D,H,P,IC,LDEB,J)
      RETURN
      ENTRY FMSCUT(XMXVOL,NR,NC,SSNG,DSNG,CTCRWN,TKCRWN)
      RETURN
      ENTRY FMSALV(IYR,X1)
      RETURN
      ENTRY FMSVTREE(I1,I2)
      RETURN
      ENTRY FMSVFL(I)
      RETURN
      ENTRY FMGETFL(I,FLNY)
      RETURN
      ENTRY FMKEY(KEY,KEYWRD)
      KEYWRD=NOFM
      RETURN
      ENTRY FMOUT
      RETURN
      ENTRY FMTRIP(ITFN,I,WEIGHT)
      RETURN
      ENTRY FMPRUN(CTCRWN)
      RETURN
      ENTRY FMATV(LACTV)
      LACTV = .FALSE.
      RETURN
      ENTRY FMLNKD(LACTV)
      LACTV = .FALSE.
      RETURN
      ENTRY FMEVSNG(X, I, J, K, X1, X2, X3, X4, I4)
      I4=1
      RETURN
      ENTRY FMEVCWD(X, I, J, I4)
      I4=1
      RETURN
      ENTRY FMEVFLM(X, I, I4)
      I4=1
      RETURN
      ENTRY FMEVSAL(X,I,I1,I2,I4)
      I4=1
      RETURN
      ENTRY FMEVMRT(X,I,I4)
      I4=1
      RETURN
      ENTRY FMEVTYP(X,I,I4)
      I4=1
      RETURN
      ENTRY FMEVCARB(X,I,I4)
      I4=1
      RETURN      
      ENTRY FMDWD(X,I,J,K,I2,I4)
      I4=1
      RETURN
      ENTRY FMEVSRT(X,I,I4)
      I4=1
      RETURN 
      ENTRY FMEVRIN(X,I,I4)
      I4=1
      RETURN                   
      ENTRY FMEVFMD(X,I,J,I4)
      I4=1
      RETURN
      ENTRY FMSADD (I,J)
      RETURN
      ENTRY FMSATV(LFM)
      RETURN
      ENTRY FMPHOTOCODE(I,CFOTO,J,K)
      RETURN
      ENTRY FMTREM(DSNG,SSNG,AX)
      RETURN
      ENTRY FMEVTBM(X1,I,I1,I2,I3,X2,X3,X4,X5,I4)
      RETURN
      ENTRY FMEVMSN(X)
      X=0.
      RETURN
      ENTRY FMEVLSF(X, I, I4)
      X=0.
      I4=1
      RETURN
C
C     ENTRIES FOR THE PPE
C
      ENTRY FMPPHV(IYR,CRBSHT,CRBLKD,CANCOV,KFMS,FMWTS,
     >             POKL,POVK,FMLOADS)
      RETURN
      ENTRY FMPPGET (XXX,I1,I2)
      RETURN
      ENTRY FMPPPUT (XXX,I1,I2)
      RETURN
      ENTRY FMSVL2(I1,X1,X2,X3,X4,L1,L2,I2)
      RETURN
      ENTRY FMSNGHT(CH7,I1,X1,X2,I2,X3)
      RETURN
      ENTRY FMSNGDK(CH7,I1,X1,X2)
      RETURN
      ENTRY FMSFALL(I1,I2,X1,X2,X3,I3,X4,X5,X6)
      RETURN
      ENTRY SNGCOE
      RETURN
      ENTRY FMCBA (I1,I2)
      RETURN
      END
