      SUBROUTINE EXORGANON
      IMPLICIT NONE
C----------
C BASE $Id: exorganon.f 0000 2018-02-14 00:00:00Z gedixon $
C
C  SATISFY EXTERNAL REFRENCES FOR THE ORGANON EXTENSION
C----------
      LOGICAL DEBUG,LKECHO
      INTEGER I,ITFN,JOSTND,IMODTY
      REAL    VAL
      REAL DANUW
      LOGICAL LDANUW
C----------
C  ENTRY ORIN   CALLED FROM INITRE
C----------
      ENTRY ORIN(DEBUG,LKECHO)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
      LDANUW = DEBUG
      LDANUW = LKECHO
C
      RETURN
C----------
C  ENTRY ORGTRIP   CALLED FROM TRIPLE
C----------
      ENTRY ORGTRIP(I,ITFN)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
      DANUW = REAL(I)
      DANUW = REAL(ITFN)
C
      RETURN
C----------
C  ENTRY ORGTAB   CALLED FROM INITRE
C----------
      ENTRY ORGTAB(JOSTND,IMODTY)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
      DANUW = REAL(JOSTND)
      DANUW = REAL(IMODTY)
C
      RETURN
C----------
C  ENTRY GETORGV   CALLED FROM EVTSTV
C----------
      ENTRY GETORGV(I,VAL)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
      DANUW = REAL(I)
C
      VAL=0.
      RETURN
C
      END