      SUBROUTINE OPCSET (ICYC)
      IMPLICIT NONE
C----------
C  **OPCSET DATE OF LAST REVISION:  07/23/08
C----------
C
C     OPTION PROCESSING ROUTINE - NL CROOKSTON - JAN 1981 - MOSCOW
C
C     SETS UP IOPCYC AS AN WITHIN CYCLE SORT INTO ASSENDING ORDER
C     OF ACTIVITY NUMBER.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'OPCOM.F77'
C
C
COMMONS
C
      INTEGER ICYC,I
C
C     IF IMG1 IS ZERO (THERE ARE NO ACTIVITIES FOR THE CYCLE);
C     THEN: RETURN
C
      IMG1=IMGPTS(ICYC,1)
      IF (IMG1 .EQ. 0) RETURN
      IMG2=IMGPTS(ICYC,2)
C
C     COPY THIS CYCLE'S PORTION OF THE ALL CYCLE SORT ARRAY INTO
C     THE WITHIN CYCLE SORT ARRAY
C
      DO 10 I=IMG1,IMG2
      IOPCYC(I)=IOPSRT(I)
   10 CONTINUE
C
C     SORT IOPCYC ON ASSENDING ACTIVITY NUMBERS.
C
      CALL IAPSRT(IMG2-IMG1+1,IACT,IOPCYC(IMG1),.FALSE.)
      RETURN
      END
