      SUBROUTINE SVCMP1
      IMPLICIT NONE
C----------
C  **SVCMP1--BASE  DATE OF LAST REVISION: 07/03/00
C----------
C
C     STAND VISUALIZATION GENERATION
C     N.L.CROOKSTON -- RMRS MOSCOW -- NOVEMBER 1998
C
C     INITIALIZE THE TREE STATUS CODES SO THEY CAN HOLD RE-
C     REFERENCING DATA.  
C
C     CALLED FROM COMPRS AND TREDEL. 
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'SVDATA.F77'
C
C
      INCLUDE 'CONTRL.F77'
C
C
      INCLUDE 'WORKCM.F77'
C
C
COMMONS
C
      INTEGER IWKCM1(MAXTRE)
      EQUIVALENCE (IWKCM1,WORK1)
      INTEGER I
C
      IF (JSVOUT.EQ.0) RETURN
      IF (NSVOBJ.EQ.0) RETURN
      IF (ITRN.EQ.0) RETURN
      DO I=1,ITRN
         IWKCM1(I)=0
      ENDDO
      RETURN
      END
