      SUBROUTINE SVOBOL (J,XJ1,YJ1,XJ2,YJ2,
     >                   K,XK1,YK1,XK2,YK2,XS,YS,KODE)
      IMPLICIT NONE
C----------
C  **SVOBOL--BASE  DATE OF LAST REVISION: 07/05/00
C----------
C
C     STAND VISUALIZATION GENERATION
C     N.L.CROOKSTON -- RMRS MOSCOW -- NOVEMBER 1998
C
C     RETURN KODE = 1 IF OBJ J OVERLAPS OBJ K
C     RETURN KODE = 0 IF NOT
C
C     IF BOTH OBJECT TYPES ARE LINES, THEN XS,YS, IS RETURNED
C     AS THE LOCATION WHERE THE LINES CROSS. OTHERWISE XS,YS
C     ARE BOTH SET TO ZERO AND SHOULD BE CONSIDERED UNDERFINED.
C
C     J AND K ARE OBJECT TYPES.  1 FOR CIRCLES, 2 FOR LINES
C     IF THE OBJECT IS A CIRCLE, THEN "X2" IS THE RADIUS 
C                                 AND "Y2" IS NOT USED,
C     IF THE OBJECT IS A LINE, THEN "X2,Y2" IS IT'S OTHER END.
C
      REAL XS,YS,YK2,XK2,YK1,XK1,YJ1,XJ1,YJ2,XJ2
      INTEGER KODE,K,J
      XS = 0.
      YS = 0.
C
      IF (J.EQ.1 .AND. K.EQ.1) THEN
C 
C        BOTH ARE CIRCLES.
C
         CALL SVCROL (XJ1,YJ1,XJ2,XK1,YK1,XK2,KODE)
C
      ELSEIF (J.EQ.1 .AND. K.EQ.2) THEN
C
C        CIRCLE AND LINE
C
         CALL SVLCOL (XJ1,YJ1,XJ2,XK1,YK1,XK2,YK2,KODE)
C
      ELSEIF (J.EQ.2 .AND. K.EQ.1) THEN
C
C        LINE AND CIRCLE
C
         CALL SVLCOL (XK1,YK1,XK2,XJ1,YJ1,XJ2,YJ2,KODE)
C
      ELSEIF (J.EQ.2 .AND. K.EQ.2) THEN
C
C        LINE AND LINE
C
         CALL SVLNOL (XJ1,YJ1,XJ2,YJ2,XK1,YK1,XK2,YK2,XS,YS,KODE)
C
      ENDIF
      RETURN
      END
