      SUBROUTINE TRNASP
      IMPLICIT NONE
C----------
C  **TRNASP DATE OF LAST REVISION:  07/23/08
C----------
C  TRNASP DECODES THE INPUT AZIMUTH VALUE GIVEN IN DEGREES AND CONVERTS
C  THE VALUE TO RADIANS. THE VALUE IS THEN ASSIGNED TO THE VARIABLE
C  ASPECT.
C----------
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'PLOT.F77'
C
C
COMMONS
C
C----------
C   CONVERT ASPECT TO RADIANS.
C----------
      ASPECT=ASPECT*0.0174533
      RETURN
      END
