      SUBROUTINE VARGET (WK3,IPNT,ILIMIT,REALS,LOGICS,INTS)
      IMPLICIT NONE
C----------
C  $Id
C----------
C
C     READ THE VARIANT SPECIFIC VARIABLES. EXCEPT FOR 2 VARIABLES FROM ESHAP.F77 (BC-ESTAB),
C     ALL VARIABLES ARE FROM BCPLOT.F77
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
      INCLUDE 'BCPLOT.F77'
      INCLUDE 'ESHAP.F77'
C
C
COMMONS
C
C     NOTE: THE ACTUAL STORAGE LIMIT FOR INTS, LOGICS, AND REALS
C     IS MAXTRE (SEE PRGPRM).
C
      INTEGER MXL,MXR,MXI,IRECLN
      PARAMETER (MXR=2,MXL=3,MXI=1,IRECLN=1024)

      INTEGER ILIMIT,IPNT,I,J,K
      INTEGER INTS(MXI)
      LOGICAL LOGICS(MXL), LC(MAXSP)
      REAL    REALS(MXR),  RC(MAXSP)
      REAL    WK3(MAXTRE)

C     GET THE INTEGER SCALARS
!     CALL IFREAD (WK3, IPNT, ILIMIT, INTS, MXI, 2) ! NONE

C     GET THE INTEGER ARRAYS
      CALL IFREAD (WK3, IPNT, ILIMIT, JDST, 3, 2)

C     GET THE LOGICAL SCALARS.
      CALL LFREAD (WK3, IPNT, ILIMIT, LOGICS, MXL, 2)
      LV2ATV  = LOGICS(1)
      LV2HTCP = LOGICS(2)
      LV2HDR  = LOGICS(3)

C     GET THE LOGICAL ARRAYS
      CALL LFREAD (WK3,IPNT,ILIMIT, LLTDGOK, MAXSP, 2)
      CALL LFREAD (WK3,IPNT,ILIMIT, LMHTDUB, MAXSP, 2)

C     GET THE LOGICAL ARRAYS FOR MORT, LTH & STG STRUCTURES
      CALL LFREAD (WK3,IPNT,ILIMIT, LC, MAXSP, 2)
      MORT%FIT   = LC
      CALL LFREAD (WK3,IPNT,ILIMIT, LC, MAXSP, 2)
      LTH%FIT    = LC
      CALL LFREAD (WK3,IPNT,ILIMIT, LC, MAXSP, 2)
      STG%FIT    = LC

C     GET THE REAL SCALARS
      CALL BFREAD (WK3,IPNT,ILIMIT,REALS,  MXR,  2)
      SEISHT = REALS(1)
      ZBRSH  = REALS(2)

C     GET THE REAL ARRAYS
      DO I=1,MRT_PY
         DO J=1,MRT_BA_UB
            DO K=1,MRT_DBH_UB
               CALL BFREAD (WK3,IPNT,ILIMIT,TMRT(I,J,K), 1, 2)
            ENDDO
         ENDDO
      ENDDO
      CALL BFREAD (WK3,IPNT,ILIMIT,DGLD1,    MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,DGBAL1,   MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,DGCR1,    MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,DGDBAL1,  MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,DGDBAL2,  MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,DGCCF1,   MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,DGDSQ1,   MAXSP,  2)

      CALL BFREAD (WK3,IPNT,ILIMIT,CRHTDBH,  MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,CRHT,     MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,CRDBH2,   MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,CRBAL,    MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,CRLNCCF,  MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,CRSD,     MAXSP,  2)

      CALL BFREAD (WK3,IPNT,ILIMIT,V2SEICOR, MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,SEICON,   MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,XHT1B,    MAXSP,  2)
      CALL BFREAD (WK3,IPNT,ILIMIT,XHT2B,    MAXSP,  2)

C     GET THE REAL ARRAYS FOR MORT STRUCTURE
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      MORT%CON    = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      MORT%INVDBH = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      MORT%DBH    = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      MORT%DBHSQ  = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      MORT%RDBH   = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      MORT%BAL    = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      MORT%SQRTBA = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      MORT%SPH    = RC

C     GET THE REAL ARRAYS FOR LTH STRUCTURE
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%MLT  = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%A1   = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%B1   = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%B2   = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%SI   = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%B3   = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%C    = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%CN   = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%CNSI = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%DG   = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%DG2  = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%DBH1 = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%DBH2 = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      LTH%HT2  = RC

C     GET THE REAL ARRAYS FOR STG STRUCTURE
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      STG%CON    = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      STG%LNHT   = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      STG%HT     = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      STG%CCF    = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      STG%BAL    = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      STG%EXPMLT = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      STG%HCCFL  = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      STG%CCFSL  = RC
      CALL BFREAD (WK3,IPNT,ILIMIT, RC,    MAXSP,  2)
      STG%SD     = RC

      RETURN
      END

      SUBROUTINE VARCHGET (CBUFF, IPNT, LNCBUF)
      IMPLICIT NONE
C
COMMONS
C
      INCLUDE 'PRGPRM.F77'
      INCLUDE 'BCPLOT.F77'

      INTEGER LNCBUF, IPNT
      CHARACTER*1 CBUFF(*), CT
      INTEGER I

C     GET THE CHARACTER DATA FOR BEC STRUCTURE
      DO I=1,3
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CT,2)
         BEC%Region(I:I) = CT
      ENDDO
      DO I=1,4
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CT,2)
         BEC%Zone(I:I) = CT
      ENDDO
      DO I=1,3
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CT,2)
         BEC%SubZone(I:I) = CT
      ENDDO
      DO I=1,5
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CT,2)
         BEC%Series(I:I) = CT
      ENDDO
      DO I=1,7
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CT,2)
         BEC%FullName(I:I) = CT
      ENDDO
      DO I=1,15
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CT,2)
         BEC%PrettyName(I:I) = CT
      ENDDO

C     GET THE CHARACTER DATA FOR MORT STRUCTURE
      DO I=1,15
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CT,2)
         MORT%PrettyName(I:I) = CT
      ENDDO

C     GET THE CHARACTER DATA FOR LTH STRUCTURE
      DO I=1,15
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CT,2)
         LTH%PrettyName(I:I) = CT
      ENDDO

C     GET THE CHARACTER DATA FOR STG STRUCTURE
      DO I=1,15
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CT,2)
         STG%PrettyName(I:I) = CT
      ENDDO

      RETURN
      END
