      SUBROUTINE ESMSGS (JOREGT)
      IMPLICIT NONE
C----------
C  **ESMSGS DATE OF LAST REVISION:   09/17/08
C----------
C
C     CALLED FROM ESIN TO PRINT HABITAT TYPE GROUPS FOR THE
C     REGENERATION ESTABLISHMENT MODEL.
C
C
      INTEGER JOREGT
C
      WRITE(JOREGT,100)
  100 FORMAT(' HABITAT TYPE GROUPS USED IN THE REGENERATION',
     &  ' ESTABLISHMENT MODEL',//,' GROUP   HABITAT TYPES',/,
     &  ' -----   ',34('-'),/)
      RETURN
      END
