      SUBROUTINE ESPREP (ISER,PNONE,PMECH,PBURN)
      IMPLICIT NONE
C----------
C  **ESPREP DATE OF LAST REVISION:  09/17/08
C----------
C     PREDICT DEFAULT SITE PREP PROBABILITIES.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'ESPARM.F77'
C
C
      INCLUDE 'ESCOMN.F77'
C
C
      INCLUDE 'PLOT.F77'
C
      REAL PBURN,PMECH,PNONE
      INTEGER ISER
C
C
COMMONS
C
C     PROB(NO SITE PREP)
C
      PNONE = 0.75
C
C     PROB(MECH SITE PREP)
C
      PMECH = 0.20
C
C     PROB(BURN SITE PREP)
C
      PBURN = 0.05
      RETURN
      END
