      SUBROUTINE RDATV (L,LTREE)
      IMPLICIT NONE
C----------
C  **RDATV       LAST REVISION:  MARCH 1, 1995
C----------
C
C  RETURNS L=TRUE, TO INDICATE THAT ROOT DISEASE MODEL IS AVAILABLE
C  WITH THE PROGRAM BEING RUN AND IS ACTUALLY BEING CALLED.
C
C  CALLED BY :
C     RDCMPR  [ROOT DISEASE]
C     RDMN1   [ROOT DISEASE]
C     RDTDEL  [ROOT DISEASE]
C     RDTRP   [ROOT DISEASE]
C     INITRE  [PROGNOSIS]
C     INTREE  [PROGNOSIS]
C
C  CALLS     :
C     NONE
C
C  PARAMETERS :
C     L     - FLAG THAT IS SET TO TRUE WHEN THE ROOT DISEASE MODEL IS
C             BEING RUN.
C     LTREE - FLAG IS TRUE IF MODEL IS BEING INITIALIZED BY THE
C             INPUT TREELIST.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77' 
      INCLUDE 'RDPARM.F77'
C
C
      INCLUDE 'RDADD.F77'
C
C
COMMONS
C
      LOGICAL L, LTREE

      L = RRTINV .OR. RRMAN
      LTREE = RRTINV

      RETURN
      END
