      SUBROUTINE RDRANI(SSEED)
C----------
C  **RDRANI      LAST REVISION:  11/06/89
C----------
C  THIS SUBROUTINE INITIALIZES THE RANDOM NUMBER GENERATOR FOR THE
C  ROOT DISEASE MODEL.
C
C  CALLED BY :
C     RDMN1   [ROOT DISEASE]
C
C  CALLS     :
C     NONE
C
C
C  PARAMETERS :
C     SSEED - SEED VALUE FOR THE ROOT DISEASE RANDOM NUMBER GENERATOR.
C
COMMON
C
C
      INCLUDE 'PRGPRM.F77'
      INCLUDE 'RDPARM.F77'
C
C
      INCLUDE 'RDADD.F77'
C
C
COMMONS
C
      ISEED = INT(SSEED)
      IF (MOD(ISEED,2) .EQ. 0) ISEED = ISEED + 1
      SS = FLOAT(ISEED)
      S0 = SS

      RETURN
      END
