      SUBROUTINE RDSSIZ(ISP,A,STCUT,ISL,ISPS,IRTSPC)
C----------
C  **RDSSIZ      LAST REVISION:  MARCH 5, 1995
C----------
C
C  SUBROUTINE FOR ASSIGNING SIZE CLASS TO STUMPS.
C
C  CALLED BY :
C     RDDAM   [ROOT DISEASE]
C     RDEND   [ROOT DISEASE]
C     RDIN    [ROOT DISEASE]
C     RDSADD  [ROOT DISEASE]
C     RDSTR   [ROOT DISEASE]
C
C  CALLS :
C     NONE
C
C  PARAMETERS :
C     ISP    -
C     A      -
C     STCUT  -
C     ISL    -
C     ISPS   -
C     IRTSPC -
C
C.... PARAMETER INCLUDE FILES
C
      INCLUDE 'PRGPRM.F77'
      INCLUDE 'RDPARM.F77'
C
      DIMENSION STCUT(5), ISPS(ITOTSP), IRTSPC(MAXSP)

      DO 100 J = 2,5
         IF (A .LT. STCUT(J-1) .OR. A .GT. STCUT(J)) GOTO 100
         ISL = J - 1
         RETURN
 100  CONTINUE

      ISL = 5

      RETURN
      END

