      SUBROUTINE ADD1 (CISN,ICOL)
      IMPLICIT NONE
C----------
C  **ADD1    DATE OF LAST REVISION:  07/31/08
C----------
C
C
      INTEGER ICOL,IVAL
C
C
C     ADDS '1' TO THE PLACE 'ICOL' IN ISN; WHERE ICOL CAN
C     RANGE BETWEEN 1 AND 7.  THIS ROUTINE WILL NOT BE CALLED IF
C     THE RESULT OF THE ADDITION WILL BE GREATER THAN 9.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
C     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--JAN 1981
C
C     CISN = INTERNAL STAND NUMBER TO BE MODIFIED
C     ICOL = COLUMN IN ISN TO BE MODIFIED.
C
C
      CHARACTER*11 CISN
C
      IF (ICOL.LT.1 .OR. ICOL.GT.7) RETURN
C
      READ  (CISN(ICOL+4:ICOL+4),'(I1)') IVAL
      IVAL=IVAL+1
      WRITE (CISN(ICOL+4:ICOL+4),'(I1)') IVAL
      RETURN
      END
