      SUBROUTINE ALSTD1
      IMPLICIT NONE
C----------
C  **ALSTD1--PPBASE   DATE OF LAST REVISION:  07/31/08
C----------
C
C     PROCESS ALL STANDS AT THE BEGINNING OF A CYCLE.  THIS ROUTINE IS
C     CALLED EVERY MASTER CYCLE REGARDLESS OF THE PROCESSING MODE.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
C     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--JULY 1982
C
C     CALLED FROM: PPMAIN
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'PPEPRM.F77'
C
C
      INCLUDE 'PPCNTL.F77'
C
C
COMMONS
C
C     LOAD THE MASTER MODE 2 INTERACTION LIST.
C
      CALL GPLOAD
C
C     SET UP THE WESTWIDE PINE BEETLE MODEL DISPERSAL RUN LISTS
C
      CALL BMSETP
C
C     IF MULTISTAND TREATEMENT SCHEDULING IS BEING USED, CALL HVALOC
C     TO SET UP THE PROCESSING FOR THIS MASTER CYCLE.
C
      IF (LHVALL) CALL HVALOC
C
      RETURN
      END
