      SUBROUTINE ALSTD2
      IMPLICIT NONE
C----------
C  **ALSTD2--PPBASE   DATE OF LAST REVISION:  07/31/08
C----------
C
C     PROCESS ALL STANDS AT THE MID POINT OF A MODE=2 CYCLE.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
C     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--JULY 1982
C
C     CALLED FROM: PPMAIN.
C
C
C     CALL THE WESTWIDE PINE BEETLE MULTI-STAND DISPERSAL MODEL DRIVER.
C
      CALL BMDRV
      RETURN
      END
