      SUBROUTINE CHDSTH (CBUFF,IPNT)
      IMPLICIT NONE
C----------
C  **CHDSTH  DATE OF LAST REVISION:  07/31/08
C----------
C
C     GET A RECORD FROM DIRECT ACCESS FILE IDAIO (DE-STASH IT).
C
C     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
C     NL CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--FEB 1987
C
C     CBUFF = CHARACTER ARRAY WHICH WILL CONTAIN INFORMATION READ
C             FROM THE RECORD.
C     IPNT  = POINTER TO LAST WORD IN BUFFER.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'PPEPRM.F77'
C
C
      INCLUDE 'PPCNTL.F77'
C
C
COMMONS
C
C
      INTEGER IPNT,ISUB,I
      CHARACTER CBUFF(IPNT)
      IF (PDEBUG) WRITE (JOPPRT,20) IRDREC,INEXR(IRDREC),IPNT
   20 FORMAT (' IN CHDSTH: IRDREC= ',I5,' INEXR(IRDREC)= ',I5,
     >        ' IPNT= ',I6)
C
C     FIND OUT WHICH ACTUAL RECORD AND FILE WE ARE GOING TO USE.
C
      ISUB=0
      DO 10 I=1,NDAFL
      IF (IRDREC.LE.NDACUM(I)) THEN
         READ (IDAIO(I),REC=IRDREC-ISUB) CBUFF
         IRDREC=INEXR(IRDREC)
         RETURN
      ELSE
         ISUB=NDACUM(I)
      ENDIF
   10 CONTINUE
C
C     THIS LOOP SHOULD NEVER EXIT.
C
      RETURN
      END
