      SUBROUTINE CHWRIT (CBUFF,IPNT,LNCBUF,CVARBL,IBEGIN)
      IMPLICIT NONE
C----------
C  **CHWRIT  DATE OF LAST REVISION:  07/31/08
C----------
C
C     WRITE A CHARACTER TO THE DIRECT ACCESS FILE.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
C     NL CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--FEB 1987
C
C     CBUFF = CHARACTER WORK STRING USED FOR A BUFFER.
C     IPNT  = POINTER TO THE CURRENT CHAR IN BUFFER.
C     LNCBUF= LENGTH OF BUFFER
C     CVARBL= THE CHARACTER WHICH IS WRITTEN TO THE BUFFER.
C     IBEGIN= SIGNAL DESCRIBING WHETHER WE ARE BEGINNING A
C             SERIES OF CALLS TO CHWRIT, IN THE MIDDLE OF A
C             SERIES OF CALLS, OR AT THE END OF A SERIES OF CALLS.
C             1 - THIS IS THE FIRST CALL IN A GROUP TO CHWRIT.
C                 THE BUFFER IS SET EMPTY, SO WE WILL
C                 BEGIN WRITING TO A NEW RECORD.
C             2 - THIS IS A MIDDLE CALL TO CHWRIT.
C             3 - THIS IS THE LAST CALL TO CHWRIT, WHICH
C                 DUMPS THE CONTENTS OF THE BUFFER, AND
C                 FINALIZES THE WRITE.
C
      INTEGER IBEGIN,IPNT,LNCBUF,I
      CHARACTER CBUFF(LNCBUF)
      CHARACTER CVARBL
      IF (IBEGIN.EQ.1) IPNT=0
      IF (IPNT.GE.LNCBUF) THEN
         CALL CHSTSH (CBUFF,LNCBUF)
         IPNT=0
      ENDIF
      IPNT=IPNT+1
      CBUFF(IPNT)=CVARBL
      IF (IBEGIN.EQ.3) THEN
         IF (IPNT.LT.LNCBUF) THEN
            DO I=IPNT+1,LNCBUF
               CBUFF(I)=' '
            ENDDO
         ENDIF
         CALL CHSTSH (CBUFF,LNCBUF)
      ENDIF
      RETURN
      END
