      SUBROUTINE GPCYCL
      IMPLICIT NONE
C----------
C  **GPCYCL  DATE OF LAST REVISION:  07/31/08
C----------
C
C     GET ALL GLOBAL ACTIVITIES FOR THIS MASTER CYCLE.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION TO PROGNOSIS.
C     P.W. THOMAS--FORESTRY SCIENCES LAB, MOSCOW, ID--MARCH 1986
C
C     SUBROUTINES CALLED :
C
C       IAPSRT - INDIRECT ASCENDING INTEGER SORT.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'PPEPRM.F77'
C
C
      INCLUDE 'PPGPCM.F77'
C
C
      INCLUDE 'PPCNTL.F77'
C
C
COMMONS
C
C
      INTEGER IDT1,IDT2,I
C
C
C
      MGPCUR=0
      IF (MIMGL.LE.0) GOTO 100
C
C     SET THE SEARCH LIST FOR THE OPTIONS.
C
      IDT1=MIY(MICYC-1)
      IDT2=MIY(MICYC)
C
C     LOOP THRU ALL OF THE GLOBAL OPTIONS.
C
      DO 40 I=1,MIMGL
      IF ((MIDATE(I).LT.IDT1).OR.(MIDATE(I).GE.IDT2)) GOTO 40
C
C     STORE THE POINTERS TO OPTIONS SCHEDULED FOR THE CURRENT MASTER
C     CYCLE.
C
      MGPCUR=MGPCUR+1
      MGPCYC(MGPCUR)=I
   40 CONTINUE
      IF (MGPCUR.LE.0) GOTO 100
C
C     SORT THE OPTIONS BY THERE DATE AND SEQUENCE NUMBER.
C
      CALL OPSORT (MGPCUR,MIDATE,IGPSEQ,MGPCYC,.FALSE.)
  100 CONTINUE
      RETURN
      END
