      SUBROUTINE IFWRIT (BUFFER,IPNT,ILIMIT,IVAR,ILEN,IBEGIN)
      IMPLICIT NONE
C----------
C  **IFWRIT--PPBASE    DATE OF LAST REVISION:  07/31/08         
C----------
C
C    SEE BFWRIT FOR A DESCRIPTION OF THIS ROUTINE
C
      REAL BUFFER(*),RSTOR
      INTEGER IVAR(*),IBEGIN,ILEN,ILIMIT,IPNT,IWORD
      INTEGER*4 ISTOR
      EQUIVALENCE (RSTOR,ISTOR)
      IF (IBEGIN.EQ.1) IPNT=0
  100 CONTINUE
      IF (ILEN.LT.1) GOTO 1000
      DO 900 IWORD=1,ILEN
      IF (IPNT.LT.ILIMIT) GOTO 500
      CALL STASH (BUFFER,ILIMIT)
      IPNT=0
  500 CONTINUE
      ISTOR=IVAR(IWORD)
      IPNT=IPNT+1
      BUFFER(IPNT)=RSTOR
  900 CONTINUE
 1000 CONTINUE
      IF (IBEGIN.EQ.3) CALL STASH (BUFFER,ILIMIT)
      RETURN
      END
