      SUBROUTINE LLDELE (IVAL,IP)
      IMPLICIT NONE
C----------
C  **LLDELE  DATE OF LAST REVISION:  07/31/08
C----------
C
C     DELETE ALL MEMBERS OF A LINK LIST BEGINNING AT IP THAT ARE
C     EQUAL TO IVAL.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION TO PROGNOSIS.
C     P.W. THOMAS--FORESTRY SCIENCES LAB, MOSCOW, ID--MARCH 1986
C
C     IVAL  = INTEGER VALUE TO BE DELETED.
C     IP    = POINTER TO BEGINNING OF LINKED LIST.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'PPEPRM.F77'
C
C
      INCLUDE 'PPLLCM.F77'
C
C
COMMONS
C
C
      INTEGER IP,IVAL,IT,IQ,IL
C
C
C     LOOP THROUGH ALL OF THE ELEMENTS THE LIST FROM MEMBER IP
C     FORWARD.
C
   10 CONTINUE
C
C     IF THE ELEMENT IS NOT EQUAL TO IVAL, BRANCH TO ACCESS THE
C     NEXT ELEMENT.
C
      IF (IELEM(IP).NE.IVAL) GOTO 20
      IT=IP
      IP=LKNEX(IP)
C
C     DISPOSE OF ELEMENT IT BY REALLOCATING IT TO FREE SPACE
C
      CALL LLDISP (IT)
      GOTO 10
   20 CONTINUE
      IQ=LKNEX(IP)
      IL=IP
   30 CONTINUE
C
C     IF THE NEXT ELEMENT IS EQUAL TO NULL, THE LIST IS FINISHED.
C
      IF (IQ.EQ.INULL) GOTO 40
      IF (IELEM(IQ).NE.IVAL) GOTO 35
      IT=IQ
      LKNEX(IL)=LKNEX(IQ)
      IQ=LKNEX(IQ)
      CALL LLDISP (IT)
      GOTO 30
   35 CONTINUE
      IL=IQ
      IQ=LKNEX(IQ)
      GOTO 30
   40 CONTINUE
      RETURN
      END
