      LOGICAL FUNCTION LLNULL (IP)
      IMPLICIT NONE
C----------
C  **LLNULL  DATE OF LAST REVISION:  07/31/08
C----------
C
C     DETERMINE IF A LINKED LIST POINTER IS NULL.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION TO PROGNOSIS.
C     P.W. THOMAS--FORESTRY SCIENCES LAB, MOSCOW, ID--MARCH 1986
C
C     PARAMETERS :
C
C       IP - LINKED LIST POINTER IN QUESTION.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'PPEPRM.F77'
C
C
      INCLUDE 'PPLLCM.F77'
C
C
COMMONS
C
      INTEGER IP
C
      LLNULL=IP.EQ.INULL
      RETURN
      END
