      SUBROUTINE LLSETP (IBEG,IEND)
      IMPLICIT NONE
C----------
C  **LLSETP  DATE OF LAST REVISION:  07/31/08
C----------
C
C     INITIALIZE BEGINNING AND ENDING POINTERS TO A LINKED LIST.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION TO PROGNOSIS.
C     P.W. THOMAS--FORESTRY SCIENCES LAB, MOSCOW, ID--MARCH 1986
C
C     PARAMETERS :
C
C       IBEG - POINTER TO BEGINNING OF LINKED LIST.
C       IEND - POINTER TO END OF LINKED LIST.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'PPEPRM.F77'
C
C
      INCLUDE 'PPLLCM.F77'
C
C
COMMONS
C
      INTEGER IEND,IBEG
C
      IBEG=INULL
      IEND=INULL
      RETURN
      END
