      SUBROUTINE PPCLOP (IUNIT)
      IMPLICIT NONE
C----------
C  **PPCLOP  DATE OF LAST REVISION:  07/31/08
C----------
C
C     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
C     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--FEB 1982.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'CONTRL.F77'
C
C
COMMONS
C
      INTEGER IUNIT
C
      IF (.NOT.LFLAG .AND. IUNIT.EQ.JOSTND) THEN
         LFLAG=.TRUE.
         WRITE (IUNIT,10)
   10    FORMAT (1X,130('-'))
      ENDIF
      RETURN
      END
