      SUBROUTINE PPEATV (L)
      IMPLICIT NONE
C----------
C  **PPEATV  DATE OF LAST REVISION:  07/31/08
C----------
C
C     RETURNS L=TRUE, TO INDICATE THAT THE PPE IS PART OF THE PROGRAM.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
C     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--SEPT 1982.
C
C       L - FLAG WHICH IF TRUE SIGNALS AN ACTIVE PPE.
C
      LOGICAL L
      L=.TRUE.
      RETURN
      END
