      SUBROUTINE PPEGET
      IMPLICIT NONE
C----------
C  **PPEGET--PPBASE   DATE OF LAST REVISION:  07/31/08
C----------
C
C     RESTART THE PARALLEL PROCESSOR BY READING ALL ITS DATA FROM
C     THE ALL-DATA FILE, AND BY READING IN THE STAND TEMPLATE IF
C     ONE IS ACTIVE.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
C     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--JULY 1982
C
C     CALLED FROM: PPIN.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'PPEPRM.F77'
C
C
      INCLUDE 'PPCNTL.F77'
C
C
      INCLUDE 'PPHVCM.F77'
C
C
      INCLUDE 'PPEXCM.F77'
C
C
      INCLUDE 'PPGPCM.F77'
C
C
      INCLUDE 'PPSPRD.F77'
C
C
      INCLUDE 'PPSPNB.F77'
C
C
      INCLUDE 'PPSPLA.F77'
C
C
      INCLUDE 'PPLLCM.F77'
C
C
      INCLUDE 'HVDNCM.F77'
C
C
      INCLUDE 'PPMDCM.F77'
C
C
      INCLUDE 'ARRAYS.F77'
C
C
COMMONS
C
      INTEGER NREALS,NLOGIC,NINTS,LNCBUF,I,J1,J2,J,IBEGIN,ILIMIT,IPNT,K
      LOGICAL LOGICS(NLOGIC)
      PARAMETER (NREALS=8,NLOGIC=36,NINTS=56)
      REAL REALS(NREALS)
      INTEGER INTS(NINTS)
      EQUIVALENCE (REALS,WK6),(LOGICS,WK6),(INTS,WK6)
C
      PARAMETER (LNCBUF=IRECLN*4)
      CHARACTER*1 CBUFF(LNCBUF),CJUNK
      EQUIVALENCE (WK3,CBUFF)
C
C     FIRST, READ IN THE ALL-DATA DIRECT ACCESS POINTERS.
C
      I=1
      J2=IRECLN-5
      IF (J2.GT.NDAREC) J2=NDAREC
      J1=1
      IF (PDEBUG) WRITE (JOPPRT,10) I,NDAREC,J1,J2
   10 FORMAT (' IN PPEGET, RECORD= ',I6,' NDAREC=',I6,' J1=',
     >        I6,' J2=',I6)
      READ (IDAIO(1),REC=I) IBEGIN,IOSTRC,IWTREC,IAVAIL,IENDFR,
     >                      (INEXR(J),J=J1,J2)
   15 CONTINUE
      I=I+1
      J1=J2+1
      J2=J2+IRECLN
      IF (J2.GT.NDAREC) J2=NDAREC
      IF (PDEBUG) WRITE (JOPPRT,10) I,NDAREC,J1,J2
      READ (IDAIO(1),REC=I) (INEXR(J),J=J1,J2)
      IF (J2.LT.NDAREC) GOTO 15
      IRDREC=IBEGIN
C
C     SET THE RECORD POINTER AND BUFFER SIZE LIMIT.
C
      ILIMIT=IRECLN
      IF (ILIMIT.GT.MAXBUF) ILIMIT=MAXBUF
      IF (PDEBUG) WRITE (JOPPRT,20) IBEGIN,ILIMIT
   20 FORMAT (' IN PPEGET, IBEGIN, ILIMIT=',2I6)
C
C     LOAD THE INTEGERS.
C
      CALL IFREAD (WK3,IPNT,ILIMIT,INTS,NINTS,1)
      MNCYC  = INTS(  1)
      MICYC  = INTS(  2)
      ISTND  = INTS(  3)
      NOSTND = INTS(  4)
      JLBWTS = INTS(  5)
      JOHIST = INTS(  6)
      INCYC  = INTS(  7)
      IDAPRT = INTS(  8)
      NPTREC = INTS(  9)
      NAVPRT = INTS( 10)
      IASVPT = INTS( 11)
      IPTELS = INTS( 12)
      NMPRTD = INTS( 13)
      JCPCMP = INTS( 14)
      JCPSUM = INTS( 15)
      JOCOPY = INTS( 16)
      IPMODI = INTS( 17)
      LNSSPL = INTS( 18)
      LNSHPL = INTS( 19)
      NBYGRP = INTS( 20)
      NAUTID = INTS( 21)
      IMSREC = INTS( 22)
      IMSEND = INTS( 23)
      IXHRVP = INTS( 24)
      NPTST1 = INTS( 25)
      NPTST2 = INTS( 26)
      NPTST3 = INTS( 27)
      MPTST1 = INTS( 28)
      MPTST2 = INTS( 29)
      NPEXCD = INTS( 30)
      MLPARM = INTS( 31)
      MXGPRM = INTS( 32)
      MIMGL  = INTS( 33)
      MGPMAX = INTS( 34)
      MGPCUR = INTS( 35)
      NRDS   = INTS( 36)
      NNBS   = INTS( 37)
      NIDS   = INTS( 38)
      NLAS   = INTS( 39)
      IFRBEG = INTS( 40)
      IFREND = INTS( 41)
      INULL  = INTS( 42)
      IHVEXT = INTS( 43)
C
C     MPB VARIABLES.
C
      JMPBPR = INTS( 44)
      MDSTND = INTS( 45)
      NDBHCL = INTS( 46)
      IMDYR1 = INTS( 47)
      IMDYR2 = INTS( 48)
      IMDYRT = INTS( 49)
      JMDVOL = INTS( 50)
      JMDDBH = INTS( 51)
      MXZNAB = INTS( 52)
      MRTYR1 = INTS( 53)
      MRTYR2 = INTS( 54)
      MRTCNT = INTS( 55)
      IDEDYR = INTS( 56)
      CALL IFREAD (WK3,IPNT,ILIMIT,MIY,MAXCY1,2)
      IF (NOSTND.GT.0) THEN
         DO 50 I=1,4
         CALL IFREAD (WK3,IPNT,ILIMIT,ISNKEY(1,I),NOSTND,2)
   50    CONTINUE
         CALL IFREAD (WK3,IPNT,ILIMIT,ISNSRT,NOSTND,2)
         CALL IFREAD (WK3,IPNT,ILIMIT,IPMODE,NOSTND,2)
         CALL IFREAD (WK3,IPNT,ILIMIT,LNSETS,NOSTND,2)
         CALL IFREAD (WK3,IPNT,ILIMIT,ISDWK1,NOSTND,2)
         CALL IFREAD (WK3,IPNT,ILIMIT,KEYLST(1,1),NOSTND,2)
         CALL IFREAD (WK3,IPNT,ILIMIT,KEYLST(1,2),NOSTND,2)
      ENDIF
      IF (IXHRVP.GT.0) THEN
         DO 60 I=1,IXHRVP
         CALL IFREAD (WK3,IPNT,ILIMIT,IHVSTA(1,I),NOSTND,2)
   60    CONTINUE
         CALL IFREAD (WK3,IPNT,ILIMIT,IHVTAB(1,1),IXHRVP,2)
         CALL IFREAD (WK3,IPNT,ILIMIT,IHVTAB(1,2),IXHRVP,2)
         CALL IFREAD (WK3,IPNT,ILIMIT,IHVTAB(1,3),IXHRVP,2)
         CALL IFREAD (WK3,IPNT,ILIMIT,LNHPLB(1,1),IXHRVP,2)
         CALL IFREAD (WK3,IPNT,ILIMIT,LNHPLB(1,2),IXHRVP,2)
      ENDIF
      CALL IFREAD (WK3,IPNT,ILIMIT,IPEXCD,NPEXCD,2)
      CALL IFREAD (WK3,IPNT,ILIMIT,NBORD ,NNBS,2)
      CALL IFREAD (WK3,IPNT,ILIMIT,NBID2 ,NIDS,2)
      CALL IFREAD (WK3,IPNT,ILIMIT,LAORD ,NLAS,2)
      IF (IFRBEG.GT.1 .OR. IFREND.LT.MXLLSZ) THEN
         CALL IFREAD (WK3,IPNT,ILIMIT,LKNEX,MXLLSZ,2)
         CALL IFREAD (WK3,IPNT,ILIMIT,IELEM,MXLLSZ,2)
      ENDIF
      CALL IFREAD (WK3,IPNT,ILIMIT,IUNLAB,IXHRVP,2)
C
C      MPB VARIABLES.
C
      CALL IFREAD (WK3,IPNT,ILIMIT,MDHAB ,MDSTND,2)
      CALL IFREAD (WK3,IPNT,ILIMIT,MDSDIX,MDSTND,2)
C
C     READ THE LOGICALS.
C
      CALL LFREAD (WK3,IPNT,ILIMIT,LOGICS,NLOGIC,2)
      LACTS  = LOGICS (  1)
      LAREAS = LOGICS (  2)
      LASTIN = LOGICS (  3)
      LBWTS  = LOGICS (  4)
      LCMPS  = LOGICS (  5)
      LEORUN = LOGICS (  6)
      LEXPON = LOGICS (  7)
      LHIST  = LOGICS (  8)
      LHVALL = LOGICS (  9)
      LHVDEB = LOGICS ( 10)
      LHVMXC = LOGICS ( 11)
      LHVUNT = LOGICS ( 12)
      LIN1ST = LOGICS ( 13)
      LMCYC  = LOGICS ( 14)
      LMDDBH = LOGICS ( 15)
      LMDDEB = LOGICS ( 16)
      LMDSPR = LOGICS ( 17)
      LMDVOL = LOGICS ( 18)
      LMINT  = LOGICS ( 19)
      LNEAR  = LOGICS ( 20)
      LNEDNG = LOGICS ( 21)
      LPRTCT = LOGICS ( 22)
      LRESTR = LOGICS ( 23)
      LSMPT  = LOGICS ( 24)
      LSNDCP = LOGICS ( 25)
      LSTYR  = LOGICS ( 26)
      LSUM   = LOGICS ( 27)
      LTMPAC = LOGICS ( 28)
      LTMPAD = LOGICS ( 29)
      PDEBUG = LOGICS ( 30)
      LHIER  = LOGICS ( 31)
C
C     MOUNTAIN PINE BEETLE VARIABLES.
C
      LMDDEB = LOGICS ( 32)
      LNEAR  = LOGICS ( 33)
      LMDSPR = LOGICS ( 34)
      LMDVOL = LOGICS ( 35)
      LMDDEB = LOGICS ( 36)
C
C     WRITE THE LOGICAL ARRAYS.
C
      CALL LFREAD (WK3,IPNT,ILIMIT,LHVOUT,IXHRVP,2)
      CALL LFREAD (WK3,IPNT,ILIMIT,LMOPEN,MIMGL,2)
      CALL LFREAD (WK3,IPNT,ILIMIT,LPAUSE,MAXCYC,2)
      CALL LFREAD (WK3,IPNT,ILIMIT,LPTST1,10,2)
      CALL LFREAD (WK3,IPNT,ILIMIT,LPTST2,10,2)
C
C     LOAD AND WRITE THE REALS  (ARRAYS FIRST).
C
      CALL BFREAD (WK3,IPNT,ILIMIT,BRCHWT,NOSTND,2)
      CALL BFREAD (WK3,IPNT,ILIMIT,AREAS,NOSTND,2)
      CALL BFREAD (WK3,IPNT,ILIMIT,SAMWTS,NOSTND,2)
      CALL BFREAD (WK3,IPNT,ILIMIT,HVPART,IXHRVP,2)
      CALL BFREAD (WK3,IPNT,ILIMIT,PTSTV1,10,2)
      CALL BFREAD (WK3,IPNT,ILIMIT,PTSTV2,NPTST2,2)
      CALL BFREAD (WK3,IPNT,ILIMIT,PTSTV3,NPTST3,2)
      CALL BFREAD (WK3,IPNT,ILIMIT,GPARMS ,MLPARM,2)
      CALL BFREAD (WK3,IPNT,ILIMIT,RDDIST ,NRDS,2)
      CALL BFREAD (WK3,IPNT,ILIMIT,BORDER ,NNBS,2)
      CALL BFREAD (WK3,IPNT,ILIMIT,EDGE   ,NIDS,2)
      CALL BFREAD (WK3,IPNT,ILIMIT,AREA   ,NLAS,2)
      CALL BFREAD (WK3,IPNT,ILIMIT,XLOC   ,NLAS,2)
      CALL BFREAD (WK3,IPNT,ILIMIT,YLOC   ,NLAS,2)
C
C     MOUNTAIN PINE BEETLE VARIABLES.
C
      IF (MRTCNT.GT.0) THEN
         CALL BFREAD (WK3,IPNT,ILIMIT,PRBMPB,MRTCNT,2)
         CALL BFREAD (WK3,IPNT,ILIMIT,VOLDED,MRTCNT,2)
         CALL BFREAD (WK3,IPNT,ILIMIT,VOLNHS,MRTCNT,2)
         CALL BFREAD (WK3,IPNT,ILIMIT,SADLPP,MRTCNT,2)
         CALL BFREAD (WK3,IPNT,ILIMIT,ELEVMD,MRTCNT,2)
         DO 210 I=1,8
         CALL BFREAD (WK3,IPNT,ILIMIT,GRNLP(1,I),MRTCNT,2)
         CALL BFREAD (WK3,IPNT,ILIMIT,PHLOEM(1,I),MRTCNT,2)
         CALL BFREAD (WK3,IPNT,ILIMIT,VOLLP(1,I),MRTCNT,2)
         CALL BFREAD (WK3,IPNT,ILIMIT,ZNUDED(1,I),MRTCNT,2)
         CALL BFREAD (WK3,IPNT,ILIMIT,CUMDED(1,I),MRTCNT,2)
         CALL BFREAD (WK3,IPNT,ILIMIT,DEDLP(1,I),MRTCNT,2)
  210    CONTINUE
         CALL BFREAD (WK3,IPNT,ILIMIT,PRNOIN,7,2)
         CALL BFREAD (WK3,IPNT,ILIMIT,ZINMOR,7,2)
         CALL BFREAD (WK3,IPNT,ILIMIT,ZMXMOR,7,2)
      ENDIF
C
C     READ THE REAL NUMBERS
C
      CALL BFREAD (WK3,IPNT,ILIMIT,REALS,NREALS,3)
      DCTOP  = REALS (  1)
      DCTPA  = REALS (  2)
      HVMXCC = REALS (  3)
      HXSIZE = REALS (  4)
C
C     MPB VARIABLES.
C
      TACRES = REALS (  5)
      RNGSHT = REALS (  6)
      RNGLNG = REALS (  7)
      PLONG  = REALS (  8)
C
C     READ THE CHARACTER DATA.
C
      K=1
      DO 300 I=1,4
      CALL CHREAD (CBUFF,IPNT,LNCBUF,CAUTID(I:I),K)
      K=2
      CALL CHREAD (CBUFF,IPNT,LNCBUF,CLBWID(I:I),2)
      CALL CHREAD (CBUFF,IPNT,LNCBUF,CMPID(I:I),2)
      CALL CHREAD (CBUFF,IPNT,LNCBUF,MGM1(I:I),2)
      CALL CHREAD (CBUFF,IPNT,LNCBUF,MGM2(I:I),2)
      CALL CHREAD (CBUFF,IPNT,LNCBUF,NSET(I:I),2)
  300 CONTINUE
      DO 310 I=1,26
      CALL CHREAD (CBUFF,IPNT,LNCBUF,NOTSET(I:I),2)
      CALL CHREAD (CBUFF,IPNT,LNCBUF,SID1(I:I),2)
      CALL CHREAD (CBUFF,IPNT,LNCBUF,SID2(I:I),2)
  310 CONTINUE
      DO 311 I=1,11
      CALL CHREAD (CBUFF,IPNT,LNCBUF,CLISN(I:I),2)
      CALL CHREAD (CBUFF,IPNT,LNCBUF,CSISN(I:I),2)
  311 CONTINUE
      IF (LNSHPL.GT.0) THEN
         DO 312 I=1,LNSHPL
         CALL CHREAD (CBUFF,IPNT,LNCBUF,SLHPLB(I:I),2)
  312    CONTINUE
      ENDIF
      IF (LNSSPL.GT.0) THEN
         DO 315 I=1,LNSSPL
         CALL CHREAD (CBUFF,IPNT,LNCBUF,SLSPLB(I:I),2)
  315    CONTINUE
      ENDIF
      IF (NOSTND.GT.0) THEN
         DO 325 J=1,NOSTND
         DO 320 I=1,11
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CISNUM(J)(I:I),2)
  320    CONTINUE
         DO 321 I=1,4
         CALL CHREAD (CBUFF,IPNT,LNCBUF,MGMIDS(J)(I:I),2)
  321    CONTINUE
         DO 322 I=1,26
         CALL CHREAD (CBUFF,IPNT,LNCBUF,STDIDS(J)(I:I),2)
  322    CONTINUE
         IF (LNSETS(J).GT.0) THEN
            DO 323 I=1,LNSETS(J)
            CALL CHREAD (CBUFF,IPNT,LNCBUF,SLSETS(J)(I:I),2)
  323       CONTINUE
         ENDIF
  325    CONTINUE
      ENDIF
      IF (LHVALL) THEN
         DO 330 J=1,IXHRVP
         IF (IHVTAB(J,1).GT.0) THEN
            DO 329 I=1,LNHPLB(J,1)
            CALL CHREAD (CBUFF,IPNT,LNCBUF,HVPLAB(J)(I:I),2)
  329       CONTINUE
         ENDIF
  330 CONTINUE
      ENDIF
      IF (NLAS.GT.0) THEN
         DO 335 J=1,NLAS
         DO 335 I=1,26
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CLAID(J)(I:I),2)
 335     CONTINUE
      ENDIF
      IF (NIDS.GT.0) THEN
         DO 337 J=1,NIDS
         DO 337 I=1,26
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CNBID1(J)(I:I),2)
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CNBID2(J)(I:I),2)
  337    CONTINUE
      ENDIF
      IF (NRDS.GT.0) THEN
         DO 338 J=1,NRDS
         DO 338 I=1,26
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CRDID(J)(I:I),2)
  338    CONTINUE
      ENDIF
      IF (NPTST2.GT.0) THEN
         DO 339 J=1,NPTST2
         DO 339 I=1,8
         CALL CHREAD (CBUFF,IPNT,LNCBUF,CPTST2(J)(I:I),2)
  339    CONTINUE
      ENDIF
      IF (MRTCNT.GT.0) THEN
         DO 345 J=1,MRTCNT
         DO 340 I=1,8
         CALL CHREAD (CBUFF,IPNT,LNCBUF,MDSTDS(J)(I:I),2)
  340    CONTINUE
         DO 345 I=1,4
         CALL CHREAD (CBUFF,IPNT,LNCBUF,MDMGID(J)(I:I),2)
  345    CONTINUE
      ENDIF
      CALL DBSPUSGET (CBUFF,IPNT,LNCBUF)
      CALL CHREAD (CBUFF,IPNT,LNCBUF,CJUNK,3)
C
C     IF AT LEAST ONE STAND HAS BEEN PROCESSED, AND IF TEMPLATING WAS
C     USED, IMSREC WILL BE GT 0, SO READ IN THE TEMPLATE.
C
      IF (IMSREC.GT.0 .AND. LTMPAC) CALL MSTRGT
C
C     RELEASE THE SPACE USED TO STORE THE PPE COMMON AREAS.
C
      IF (PDEBUG) WRITE (JOPPRT,400) IBEGIN,IOSTRC
  400 FORMAT (' IN PPEGET: IBEGIN, IOSTRC=',2I6)
      CALL SPARLS (IBEGIN,IOSTRC)
C
      RETURN
      END
