      SUBROUTINE PPWEIG (II,WEIGHT)
      IMPLICIT NONE
C----------
C  **PPWEIG  DATE OF LAST REVISION:  07/31/08
C----------
C
C     COMPUTES THE WEIGHTING FACTOR USED BY THE PPE.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
C     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--FEB 1982.
C
C     CALLED FROM PPIN - PROCESS PPE KEYWORDS.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'PPEPRM.F77'
C
C
      INCLUDE 'PPCNTL.F77'
C
C
COMMONS
C
C
      INTEGER II,I,IG
      REAL WEIGHT,SMWT
C
C     IF THE STAND POINTER 'II' IS ZERO, THEN USE THE CURRENT VALUE
C     OF ISTND.
C
      I=ISTND
      IF (II.GT.0) I=II
C
C     COMPUTE THE WEIGHTING FACTOR FOR THE STAND.
C
      IF (PDEBUG) THEN
         WRITE (JOPPRT,*) ' IN PPWEIGH AREAS(1-5)= ',(AREAS(IG),IG=1,5)
         WRITE (JOPPRT,*) '           SAMWTS(1-5)= ',(SAMWTS(IG),IG=1,5)
      ENDIF

      IF (LAREAS) THEN
         SMWT=AREAS(I)
      ELSE
         SMWT=SAMWTS(I)
      ENDIF
      IF (SMWT.LE.0.0) SMWT=1.0
      WEIGHT = BRCHWT(I)*SMWT
      IF (PDEBUG) WRITE(JOPPRT,*) 'LEAVING PPWEIGH I,BRCHWT,WEIGHT= ',
     >                            I,BRCHWT(I),WEIGHT
      RETURN
      END
