      SUBROUTINE PRTBRH (JOUT,CISN)
      IMPLICIT NONE
C----------
C  **PRTBRH  DATE OF LAST REVISION:  07/31/08
C----------
C
C     PRINTS THE BRANCHING PART OF THE INTERNAL STAND NUMBER.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
C     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--JULY 1982
C
C     JOUT = LOGICAL UNIT NUMBER FOR PRINTOUT.
C     CISN = INTERNAL STAND NUMBER.
C
      INTEGER JOUT,NBR,I
      CHARACTER*11 CISN
C
C     FIND OUT HOW MANY NODES EXIST...AND PRINT THAT MANY.
C
      CALL RITCOL (CISN(5:11),NBR)
      IF (NBR.GT.0) THEN
         WRITE (JOUT,10) CISN(1:4),((I-4),CISN(I:I),I=5,(NBR+4))
   10    FORMAT (' STAND: ',A4,',',
     >          (T13,(7(' NODE ',I1,' BRANCH ',A1,:';'))))
      ENDIF
      RETURN
      END
