      SUBROUTINE PRTSPA
      IMPLICIT NONE
C----------
C  **PRTSPA  DATE OF LAST REVISION:  07/31/08
C----------
C
C     KEEPS TRACK OF SPACE ON DIRECT ACCESS SPACE FOR PRINT DATA.
C
C     CALLED FROM: STOPRT
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'PPEPRM.F77'
C
C
      INCLUDE 'PPCNTL.F77'
C
C
COMMONS
C
C
C     INCREMENT PRINT DATA POINTER, CHECK FOR AVAILABLE SPACE.
C
      IF (NAVPRT.GE.0) THEN
         NAVPRT=NAVPRT+1
         IF (NPTREC.GT.0 .AND. NAVPRT.GT.NPTREC) THEN
            WRITE (JOPPRT,10) NAVPRT,NPTREC
   10       FORMAT (/' PRINT-DATA FILE RECORD REQUEST= ',I8,
     >               '; MAX RECORDS ALLOWED= ',I8)
C
C           SHUT DOWN THE PRINT-DATA WRITE
C
            NAVPRT=-1
            CALL PPERRP (.TRUE.,1)
         ENDIF
      ENDIF
      RETURN
      END
