      SUBROUTINE SRTISN (NMPRTD,CISNS,IPTS,MXISN,NENISN,IENISN)
      IMPLICIT NONE
C----------
C  **SRTISN  DATE OF LAST REVISION:  07/31/08
C----------
C
C     ORDERS IPTS SUCH THAT ITS MEMBERS POINT TO INTERNAL
C     STAND NUMBERS (CISNS) IN ASSENDING SEQUENCE; AND ESTABLISHES
C     IENISN SUCH THAT POSITION I POINTS TO THE LAST PLACE IN IPTS
C     ASSOCIATED WITH THE I-TH UNIQUE ROOT ISN.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
C     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--JAN 1981
C
C     CALLED FROM SNDTBS - GENERATE AND PRINT STAND TABLES.
C
C     NMPRTD= THE LENGTH OF ISNS AND IPTS.
C     CISNS = THE ARRAY OF INTERNAL STAND NUMBERS.
C     IPTS  = POINTER ARRAY TO CISNS.
C     MXISN = MAX LENGTH OF IENISN.
C     NENISN= RETURNED AS THE ACTUAL LENGTH OF IENISN, AND IS
C             THEREFORE EQUAL TO THE NUMBER OF UNIQUE ROOT ISN'S.
C     IENISN= POSITION I POINTS TO THE LAST PLACE IN IPTS
C             ASSOCIATED WITH THE ITH UNIQUE ROOT ISN.
C
      CHARACTER CISNS(NMPRTD)*11,CIFST*4
      INTEGER IPTS(NMPRTD),IENISN(NMPRTD),MXISN,NMPRTD,J,I,NENISN
      NENISN=0
C
C     IF THE NUMBER OF ENTERIES IN IPTS IS ZERO; THEN: RETURN
C
      IF (NMPRTD.EQ.0) RETURN
C
C     SORT THE POINTER ARRAY ON CISNS
C
      CALL C11SRT (NMPRTD,CISNS,IPTS,.TRUE.)
C
C     DEFINE IENISN
C
      J=IPTS(1)
      CIFST=CISNS(J)(1:4)
      IF (NMPRTD.GT.1) GOTO 10
      NENISN=1
      IENISN(1)=1
      RETURN
C
C
   10 CONTINUE
      DO 20 I=2,NMPRTD
      J=IPTS(I)
      IF (CIFST.EQ.CISNS(J)(1:4)) GOTO 20
      NENISN=NENISN+1
      IF (NENISN.GT.MXISN) CALL PPERRP (.FALSE.,10)
      IENISN(NENISN)=I-1
      CIFST=CISNS(J)(1:4)
   20 CONTINUE
      NENISN=NENISN+1
      IF (NENISN.GT.MXISN) CALL PPERRP (.FALSE.,10)
      IENISN(NENISN)=NMPRTD
      RETURN
      END
