      SUBROUTINE EXPPNB
      IMPLICIT NONE
C----------
C BM $Id: exppnb.f 0000 2018-02-14 00:00:00Z gedixon $
C----------
C
C     VARIANT DEPENDENT EXTERNAL REFERENCES FOR THE
C     PARALLEL PROCESSING EXTENSION.
C
      REAL BAB(9),BBA,BREL,CPCCF,CDBAL,CLBA,D,PCCFO,CCFO,BALO
      REAL BAO,XPPDDS,BX,XPPMLT
      REAL DANUW
C
C
C     CALLED TO COMPUTE THE DDS MODIFIER THAT ACCOUNTS FOR THE DENSITY
C     OF NEIGHBORING STANDS (CALLED FROM DGF).
C
      ENTRY PPDGF (XPPDDS,BAO,BALO,CCFO,PCCFO,D,CLBA,CDBAL,CPCCF,
     &             BREL,BBA)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
      DANUW = XPPDDS
      DANUW = BAO
      DANUW = BALO
      DANUW = CCFO
      DANUW = PCCFO
      DANUW = D
      DANUW = CLBA
      DANUW = CDBAL
      DANUW = CPCCF
      DANUW = BREL
      DANUW = BBA
C
      RETURN
C
C     CALLED TO COMPUTE THE REGENT MULTIPLIER THAT ACCOUNTS FOR
C     THE DENSITY OF NEIGHBORING STANDS (CALLED FROM REGENT).
C
      ENTRY PPREGT (XPPMLT,BX,BAB,CCFO)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
      DANUW = XPPMLT
      DANUW = BX
      DANUW = BAB(1)
      DANUW = CCFO
C
      RETURN
      END
