      SUBROUTINE EXPPNB
      IMPLICIT NONE
C----------
C  **EXPPNB-BM  DATE OF LAST REVISION:  02/20/08
C----------
C
C     VARIANT DEPENDENT EXTERNAL REFERENCES FOR THE
C     PARALLEL PROCESSING EXTENSION.
C
      REAL BAB(9),BBA,BREL,CPCCF,CDBAL,CLBA,D,PCCFO,CCFO,BALO
      REAL BAO,XPPDDS,BX,XPPMLT
C
C
C     CALLED TO COMPUTE THE DDS MODIFIER THAT ACCOUNTS FOR THE DENSITY
C     OF NEIGHBORING STANDS (CALLED FROM DGF).
C
      ENTRY PPDGF (XPPDDS,BAO,BALO,CCFO,PCCFO,D,CLBA,CDBAL,CPCCF,
     &             BREL,BBA)
      RETURN
C
C     CALLED TO COMPUTE THE REGENT MULTIPLIER THAT ACCOUNTS FOR
C     THE DENSITY OF NEIGHBORING STANDS (CALLED FROM REGENT).
C
      ENTRY PPREGT (XPPMLT,BX,BAB,CCFO)
      RETURN
      END
