      SUBROUTINE VARPUT (WK3,IPNT,ILIMIT,REALS,LOGICS,INTS)
      IMPLICIT NONE
C----------
C  **VARPUT--CR   DATE OF LAST REVISION:  09/18/08
C----------
C
C     WRITE THE VARIANT SPECIFIC VARIABLES.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION TO PROGNOSIS.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'GGCOM.F77'
C
C
COMMONS
C
C     NOTE: THE ACTUAL STORAGE LIMIT FOR INTS, LOGICS, AND REALS
C     IS MAXTRE (SEE PRGPRM).  
C
      INTEGER ILIMIT,IPNT,MXL,MXI,MXR
      PARAMETER (MXL=1,MXI=1,MXR=5)
      LOGICAL LOGICS(*)
      REAL WK3(MAXTRE)
      INTEGER INTS(*)
      REAL REALS(*)
C
C     STORE THE INTEGER SCALARS IN THE ARRAY INTS
C
      INTS ( 1) =  IGFOR
      CALL IFWRIT (WK3, IPNT, ILIMIT, INTS, MXI, 2)
C
C     WRITE THE INTEGER ARRAYS
C
      CALL IFWRIT (WK3, IPNT, ILIMIT, IEQMAP, 11*MAXSP, 2)
C
C     STORE THE LOGICAL SCALARS.
C
C**   CALL LFWRIT (WK3, IPNT, ILIMIT, LOGICS, MXL, 2)
C
C     STORE THE REAL SCALARS IN THE ARRAY REALS.
C
      REALS( 1) =  AGERNG
      REALS( 2) =  SEEDS
      REALS( 3) =  TPAT
      REALS( 4) =  DSTAG
      REALS( 5) =  BAINIT
      CALL BFWRIT (WK3, IPNT, ILIMIT, REALS, MXR, 2)
C
C     WRITE THE REAL ARRAYS
C
      CALL BFWRIT (WK3, IPNT, ILIMIT, BCLAS,  MAXSP*41, 2)
      CALL BFWRIT (WK3, IPNT, ILIMIT, TBA,    MAXSP,    2)
      CALL BFWRIT (WK3, IPNT, ILIMIT, BAU,    41,       2)
      CALL BFWRIT (WK3, IPNT, ILIMIT, BARK1,  MAXSP,    2)
      CALL BFWRIT (WK3, IPNT, ILIMIT, BARK2,  MAXSP,    2)
      CALL BFWRIT (WK3, IPNT, ILIMIT, DBHMAX, MAXSP,    2)
      CALL BFWRIT (WK3, IPNT, ILIMIT, TCLAS,  MAXSP*41, 2)
      CALL BFWRIT (WK3, IPNT, ILIMIT, BREAK,  MAXSP,    2)
      CALL BFWRIT (WK3, IPNT, ILIMIT, SITELO, MAXSP,    2)
      CALL BFWRIT (WK3, IPNT, ILIMIT, SITEHI, MAXSP,    2)
C
      RETURN
      END
