      SUBROUTINE BWECRC (XHT,IHTC,ICRC1,ICRC2)
      IMPLICIT NONE
C----------
C WSBWE $Id$
C----------
C
C     SELECT THE HEIGHT CLASS AND CROWN CLASS INDICIES.
C
C     PART OF THE WESTERN SPRUCE BUDWORM MODEL/PROGNOSIS LINKAGE CODE.
C     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--JUNE 1983
C
C     CALLED FROM :
C
C       BWESIT - CREATE A BUDWORM STAND FROM A PROGNOSIS STAND.
C       BWEDAM - COMPUTE PERIODIC DAMAGE BY BUDWORM TO PROGNOSIS
C                SAMPLE TREES.
C       BWEPRB - ADJUST PROPORTION OF RETAINED BIOMASS ARRAY.
C
C     PARAMETERS :
C
C     XHT   = TREE HEIGHT IN FEET.
C     IHTC  = HEIGHT CLASS NUMBER, WHERE 1= 0 TO 7 METERS,
C             2= 7 TO 14 METERS, AND 3= 14 PLUS METERS.
C     ICRC1 = THE INDEX POINTING TO THE FIRST CROWN CLASS FOR THE TREE.
C     ICRC2 = THE INDEX POINTING TO THE LAST CROWN CLASS FOR THE TREE.
C
C  Revision History:
C    14-JUL-2010 Lance R. David (FMSC)
C       Added IMPLICIT NONE and declared variables as needed.
C----------
      INTEGER ICRC1, ICRC2, IHTC
      REAL    XHT
      
      IHTC=1
      IF (XHT.LT.23.) GOTO 10
      IHTC=2
      IF (XHT.LT.46.) GOTO 10
      IHTC=3
   10 CONTINUE
      ICRC2=IHTC*3
      ICRC1=ICRC2-2
      RETURN
      END
