      SUBROUTINE EXCFIM
      IMPLICIT NONE
C----------
C FIRE-BASE $Id$
C----------
C
C     EXTRA EXTERNAL REFERENCES FOR THE CFIM (Crown Fire Initiation Model) FROM FVS-BC
C     FOR USE WHEN CFIM IS NOT LINKED TO FFE
C
      CHARACTER*8 CFTMP
      INTEGER  IYR,FMOIS,CANBURN,FCLS,FLAME,FMD
      REAL     ROS,INTSTY,UWIND,IBYRAM
      REAL DANUW
      CHARACTER*8 CDANUW
C----------
C  ENTRY FMCANC
C----------
      ENTRY FMCANC (IYR,FMOIS,CFTMP,CANBURN,ROS,INTSTY,FCLS)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
      DANUW = REAL(IYR)
      DANUW = REAL(FMOIS)
      DANUW = REAL(CANBURN)
      DANUW = REAL(FCLS)
      CDANUW(1:8) = CFTMP(1:8)
      DANUW = ROS
      DANUW = INTSTY
C
      RETURN
C----------
C  ENTRY FMCFIM
C----------
      ENTRY FMCFIM(IYR,FMD,UWIND,IBYRAM,FLAME,CANBURN,ROS)      
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
      DANUW = REAL(IYR)
      DANUW = REAL(FMD)
      DANUW = REAL(FLAME)
      DANUW = REAL(CANBURN)
      DANUW = UWIND
      DANUW = IBYRAM
      DANUW = ROS
C
      RETURN
      END
