      FUNCTION BRATIO(IS,D,H)
      IMPLICIT NONE
C----------
C KT $Id$
C----------
C
C FUNCTION TO COMPUTE BARK RATIOS. THIS ROUTINE IS VARIANT SPECIFIC
C AND EACH VARIANT USES ONE OR MORE OF THE ARGUMENTS PASSED TO IT.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'COEFFS.F77'
C
C
COMMONS
      INTEGER IS
      REAL H,D,BRATIO
      REAL RDANUW
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
      RDANUW = H
      RDANUW = D
C
      BRATIO=BKRAT(IS)
      RETURN
      END
