      SUBROUTINE SVDFLN (X1,Y1,X2,Y2,A,B,KODE)
      IMPLICIT NONE
C----------
C BASE $Id$
C----------
C
C     STAND VISUALIZATION GENERATION
C     N.L.CROOKSTON -- RMRS MOSCOW -- NOVEMBER 1998
C
C     RETURNS A AND B FOR THE FORMULA Y=A+BX OF THE LINE
C     KODE = 0 IF OK, 1 = INFINITE SLOPE, NO INTERCEPT
C
      REAL X1,Y1,X2,Y2,A,B
      INTEGER KODE
      A = 0.
      B = 0.
      KODE = 0
C
C     IF THE Y'S ARE EQUAL, THEN WE HAVE 0 SLOPE.  THE INTERCEPT
C     IS Y1, SLOPE IS SET TO 0.
C
      IF (ABS(Y1-Y2) .LT. .000001) THEN
         A = Y1
         RETURN
      ENDIF
C
C     IF THE X'S ARE EQUAL, THEN WE HAVE INFINITE SLOPE AND THE
C     INTERCEPT IS UNDEFINED.
C
      IF (ABS(X1-X2) .LT. .000001) THEN
         KODE = 1
         RETURN
      ENDIF
C
      B = (Y2-Y1) / (X2-X1)
C
      A = Y1 - (B*X1)
C
      RETURN
      END
