      SUBROUTINE DGBND (ISPC,DBH,DDG)
C----------
C CANADA-ON $Id$
C----------
C  THIS SUBROUTINE IS USED TO INSURE THAT A MAXIMUM VALUE FOR DG
C  IS NOT EXCEEDED.
C
C ALL SPECIES USE THE SAME BOUNDING FUNCTION.
C THIS FUNCTION IS FROM THE WC VARIANT, BUT WITH THE MAXIMUM VALUE 
C LOWERED FROM 7.92 TO 6.0 (ARBITRARILY)
C----------
      IF(DBH .GT. 150.)DBH=150.
      DGMAX = 6.0*EXP(-0.03*DBH)
      IF(DDG .GT. DGMAX) DDG = DGMAX
      IF(DDG .LT. 0.0) DDG = 0.0
      RETURN
      END
