      SUBROUTINE RGNTHW(LESTB,ITRNIN)
      IMPLICIT NONE
C----------
C CANADA-ON $Id$
C----------
C  ROUTINE NOT USED IN ON VARIANT; PRESERVED FOR COMPATIBILTIY WITH OLD CALLS

      LOGICAL LESTB
	INTEGER ITRNIN

      RETURN
      END
