      SUBROUTINE ESSUBH (I,HHT,EMSQR,DILATE,DELAY,EL,IHTSER,
     &  GENTIM,TRAGE)
      IMPLICIT NONE
C----------
C WS $Id: essubh.f 0000 2018-02-14 00:00:00Z gedixon $
C----------
C
C     ASSIGNS HEIGHTS TO SUBSEQUENT AND PLANTED TREE RECORDS
C     CREATED BY THE ESTABLISHMENT MODEL.
C
C
C     COMING INTO ESSUBH, TRAGE IS THE AGE OF THE TREE AS SPECIFIED ON 
C     THE PLANT OR NATURAL KEYWORD.  LEAVING ESSUBH, TRAGE IS THE NUMBER 
C     BETWEEN PLANTING (OR NATURAL REGENERATION) AND THE END OF THE 
C     CYCLE.  AGE IS TREE AGE UP TO THE TIME REGENT WILL BEGIN GROWING 
C     THE TREE.
C----------
C  COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'ESPARM.F77'
C
C
      INCLUDE 'ESCOMN.F77'
C
C
      INCLUDE 'PLOT.F77'
C
COMMONS
C----------
C   DECLARATIONS
C----------
      INTEGER I,N,IHTSER,ITIME
      REAL    EMSQR,DILATE,EL,HHT,DELAY,GENTIM,TRAGE,AGE,SI
      REAL DANUW
C----------
C     SPECIES LIST FOR WESTERN SIERRAS VARIANT.
C
C     1 = SUGAR PINE (SP)                   PINUS LAMBERTIANA
C     2 = DOUGLAS-FIR (DF)                  PSEUDOTSUGA MENZIESII
C     3 = WHITE FIR (WF)                    ABIES CONCOLOR
C     4 = GIANT SEQUOIA (GS)                SEQUOIADENDRON GIGANTEAUM
C     5 = INCENSE CEDAR (IC)                LIBOCEDRUS DECURRENS
C     6 = JEFFREY PINE (JP)                 PINUS JEFFREYI
C     7 = CALIFORNIA RED FIR (RF)           ABIES MAGNIFICA
C     8 = PONDEROSA PINE (PP)               PINUS PONDEROSA
C     9 = LODGEPOLE PINE (LP)               PINUS CONTORTA
C    10 = WHITEBARK PINE (WB)               PINUS ALBICAULIS
C    11 = WESTERN WHITE PINE (WP)           PINUS MONTICOLA
C    12 = SINGLELEAF PINYON (PM)            PINUS MONOPHYLLA
C    13 = PACIFIC SILVER FIR (SF)           ABIES AMABILIS
C    14 = KNOBCONE PINE (KP)                PINUS ATTENUATA
C    15 = FOXTAIL PINE (FP)                 PINUS BALFOURIANA
C    16 = COULTER PINE (CP)                 PINUS COULTERI
C    17 = LIMBER PINE (LM)                  PINUS FLEXILIS
C    18 = MONTEREY PINE (MP)                PINUS RADIATA
C    19 = GRAY PINE (GP)                    PINUS SABINIANA
C         (OR CALIFORNIA FOOTHILL PINE)
C    20 = WASHOE PINE (WE)                  PINUS WASHOENSIS
C    21 = GREAT BASIN BRISTLECONE PINE (GB) PINUS LONGAEVA
C    22 = BIGCONE DOUGLAS-FIR (BD)          PSEUDOTSUGA MACROCARPA
C    23 = REDWOOD (RW)                      SEQUOIA SEMPERVIRENS
C    24 = MOUNTAIN HEMLOCK (MH)             TSUGA MERTENSIANA
C    25 = WESTERN JUNIPER (WJ)              JUNIPERUS OCIDENTALIS
C    26 = UTAH JUNIPER (UJ)                 JUNIPERUS OSTEOSPERMA
C    27 = CALIFORNIA JUNIPER (CJ)           JUNIPERUS CALIFORNICA
C    28 = CALIFORNIA LIVE OAK (LO)          QUERCUS AGRIFOLIA
C    29 = CANYON LIVE OAK (CY)              QUERCUS CHRYSOLEPSIS
C    30 = BLUE OAK (BL)                     QUERCUS DOUGLASII
C    31 = CALIFORNIA BLACK OAK (BO)         QUERQUS KELLOGGII
C    32 = VALLEY OAK (VO)                   QUERCUS LOBATA
C         (OR CALIFORNIA WHITE OAK)
C    33 = INTERIOR LIVE OAK (IO)            QUERCUS WISLIZENI
C    34 = TANOAK (TO)                       LITHOCARPUS DENSIFLORUS
C    35 = GIANT CHINQUAPIN (GC)             CHRYSOLEPIS CHRYSOPHYLLA
C    36 = QUAKING ASPEN (AS)                POPULUS TREMULOIDES
C    37 = CALIFORNIA-LAUREL (CL)            UMBELLULARIA CALIFORNICA
C    38 = PACIFIC MADRONE (MA)              ARBUTUS MENZIESII
C    39 = PACIFIC DOGWOOD (DG)              CORNUS NUTTALLII
C    40 = BIGLEAF MAPLE (BM)                ACER MACROPHYLLUM
C    41 = CURLLEAF MOUNTAIN-MAHOGANY (MC)   CERCOCARPUS LEDIFOLIUS
C    42 = OTHER SOFTWOODS (OS)
C    43 = OTHER HARDWOODS (OH)
C
C  SURROGATE EQUATION ASSIGNMENT:
C
C    FROM EXISTING WS EQUATIONS --
C      USE 1(SP) FOR 11(WP) AND 24(MH) 
C      USE 2(DF) FOR 22(BD)
C      USE 3(WF) FOR 13(SF)
C      USE 4(GS) FOR 23(RW)
C      USE 8(PP) FOR 18(MP)
C      USE 34(TO) FOR 35(GC), 36(AS), 37(CL), 38(MA), AND 39(DG)
C      USE 31(BO) FOR 28(LO), 29(CY), 30(BL), 32(VO), 33(IO), 40(BM), AND
C                     43(OH)
C
C    FROM CA VARIANT --
C      USE CA11(KP) FOR 12(PM), 14(KP), 15(FP), 16(CP), 17(LM), 19(GP), 20(WE), 
C                       25(WJ), 26(WJ), AND 27(CJ)
C      USE CA12(LP) FOR 9(LP) AND 10(WB)
C
C    FROM SO VARIANT --
C      USE SO30(MC) FOR 41(MC)
C
C    FROM UT VARIANT --
C      USE UT17(GB) FOR 21(GB)
C----------
C  DUMMY ARGUMENT NOT USED WARNING SUPPRESSION SECTION
C----------
      DANUW = DILATE
      DANUW = EL
      DANUW = EMSQR
      DANUW = REAL(IHTSER)
C
C----------
      N=INT(DELAY+0.5)
      IF(N.LT.-3) N=-3
      DELAY=FLOAT(N)
      ITIME=INT(TIME+0.5)
      IF(N.GT.ITIME) DELAY=TIME
      AGE=TIME-DELAY-GENTIM+TRAGE
      IF(AGE.LT.1.0) AGE=1.0
      TRAGE=TIME-DELAY
C
      SI= SITEAR(I)
C
      SELECT CASE (I)
C----------
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 42=OS
C----------
      CASE (42)
        HHT = 1.0
C----------
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 1=SP, 11=WP, 24=MH
C----------
      CASE (1,11,24)
        HHT = 2.0
C----------
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 2=DF, 22=BD
C----------
      CASE (2,22)
        HHT = 1.0
C----------
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 3=WF, 13=SF
C----------
      CASE (3,13)
        HHT = 2.0
C----------
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 4=GS, 23=RW
C----------
      CASE (4,23)
        HHT = 3.0
C----------
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 5=IC
C----------
      CASE (5)
        HHT = 2.0
C----------
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 28=LO, 29=CY, 30=BL, 31=BO, 
C----------                              32=VO, 33=IO, 40=BM, 43=OH
      CASE (28:33,40,43)
        HHT = 7.0
C----------
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 6=JP
C----------
      CASE (6)
        HHT = 0.8
C----------
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 7=RF
C----------
      CASE (7)
        HHT = 5.0
C----------
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 8=PP, 18=MP
C----------
      CASE (8,18)
        HHT = 4.0
C----------
C  FROM THE CA VARIANT
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 9=LP, 10=WB
C----------
      CASE (9,10)
        HHT = 3.0
C----------
C  FROM THE CA VARIANT
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 12=PM, 14=KP, 15=FP, 16=CP, 17=LM,
C                                 19=GP, 20=WE, 25=WJ, 26=UJ, 27=CJ
C----------
      CASE (12,14:17,19:20,25:27)
        HHT = 3.0
C----------
C  FROM THE UT VARIANT
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 21=GB
C----------
      CASE (21)
        HHT = 0.5
C----------
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 34=TO, 35=GC, 36=AS, 37=CL,
C                                        38=MA, 39=DG
C----------
      CASE (34:39)
        HHT = 7.0
C----------
C  FROM THE SO VARIANT
C  HEIGHT OF TALLEST SUBSEQUENT SPECIES: 41=MC
C----------
      CASE (41)
        HHT = ((1.47043 + 0.23317*SI)/(31.56252 - 0.05586*SI))*AGE
C
      END SELECT
C
      RETURN
      END
C**END OF CODE SEGMENT