      SUBROUTINE FORKOD
      IMPLICIT NONE
C----------
C  **FORKOD--EC   DATE OF LAST REVISION:  02/24/12
C----------
C     TRANSLATES FOREST CODE INTO A SUBSCRIPT, IFOR, AND IF
C     KODFOR IS ZERO, THE ROUTINE RETURNS THE DEFAULT CODE.
C----------
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'PLOT.F77'
C
C
      INCLUDE 'CONTRL.F77'
C
C
COMMONS
C----------
C  NATIONAL FORESTS:
C  606 = MT HOOD
C  608 = OKANOGAN
C  617 = WENATCHEE
C  699 = OKANOGAN (TONASKET RD)
C  603 = GIFFORD PINCHOT (MAPPED TO WENATCHEE)
C        GP WAS IN THE AREA OF INTEREST BUT NO DATA WERE AVAILABLE;
C        THUS IT IS MAPPED TO THE WENATCHEE FOR PROCESSING.
C  613 = MT BAKER - SNOQUALMIE (MAPPED TO WENATCHEE)
C
C  NOTE: GIFFORD PINCHOT GETS IGL=2 AND MT BAKER/SNOQUALMIE GETS IGL=3.
C        THIS IS SO FOREST SPECIFIC HT-DBH EQNS CAN BE INDEXED IN
C        SUBROUTINE **HTDBH**.
C----------
      INTEGER JFOR(7),KFOR(7),NUMFOR,I
      DATA JFOR/606,608,617,699,603,613, 0 /, NUMFOR /6/
      DATA KFOR/4*1,2,3,1/
C
      IF (KODFOR .EQ. 0) GOTO 30
      DO 10 I=1,NUMFOR
      IF (KODFOR .EQ. JFOR(I)) GOTO 20
   10 CONTINUE
      CALL ERRGRO (.TRUE.,3)
      WRITE(JOSTND,55) JFOR(IFOR)
  55  FORMAT(T13,'FOREST CODE USED IN THIS PROJECTION IS ',I4)
      GOTO 30
   20 CONTINUE
      IF(I .EQ. 5)THEN
        WRITE(JOSTND,21)
   21   FORMAT(T13,'GIFFORD PINCHOT NF (603) BEING MAPPED TO ',
     &  'WENATCHEE (617) FOR FURTHER PROCESSING.')
        I=3
        IFOR=I
        IGL=2
        GO TO 30
      ELSEIF(I .EQ. 6)THEN
        WRITE(JOSTND,22)
   22   FORMAT(T13,'MT BAKER-SNOQUALMIE NF (613) BEING MAPPED TO ',
     &  'WENATCHEE (617) FOR FURTHER PROCESSING.')
        I=3
        IFOR=I
        IGL=3
        GO TO 30
      ENDIF
      IFOR=I
      IGL=KFOR(I)
   30 CONTINUE
      KODFOR=JFOR(IFOR)
C
      RETURN
      END
