      SUBROUTINE PPREGT (XPPMLT,BAO,BALO,BRHT,BSBA,BBAL)
      IMPLICIT NONE
C----------
C  **PPREGT--CI DATE OF LAST REVISION:  09/18/08
C----------
C
C     IF ARGUMENT LIST CHANGES, ALSO CHANGE EXPPNB ROUTINE
C
C     COMPUTE THE REGENT MULTIPLIER THAT ACCOUNTS FOR THE DENSITY
C     OF NEIGHBORING STANDS.
C
C     PART OF THE PARALLEL PROCESSING EXTENSION OF PROGNOSIS SYSTEM.
C     N.L. CROOKSTON--FORESTRY SCIENCES LAB, MOSCOW, ID--NOV 1992
C
C     MODIFIED FOR CENTRAL IDAHO BY   GARY DIXON -- FT COLLINS, CO
C                                     FOREST MANAGEMENT SERVICE CENTER
C     CALLED FROM: GRADD.
C
COMMONS
C
C
      INCLUDE 'PPDNCM.F77'
C
C
COMMON
C----------
C     IF THE NEIGHBOR DENSITY EFFECTS ARE BEING INCLUDED, THEN
C     CALCULATE THEM, OTHERWISE, RETURN.
C
C     FIRST TERM IS TOTAL STAND BA
C     SECOND TERM IS BAL
C       NOTE: ASSUME ADDITIONAL STAND BA WILL BE IN BIGGER TREES
C     THIRD TERM IS BAL*RELHT INTERACTION
C
C
      REAL BBAL,BSBA,BRHT,BALO,BAO,XPPMLT
C
C
C----------
      IF (LNEDNS) THEN
         XPPMLT=     BSBA*(AMAX1(0.0,PDBAN-BAO))  +
     >               BBAL*(AMAX1(0.0,PDBAN-BALO)) +
     >               BRHT*(AMAX1(0.0,PDBAN-BALO))
      ENDIF
      RETURN
      END
