# $Id$

#
#  the FVSbcc test files are not currently being maintained.
#  remove # before statements to run tests
#
# all : climbc mgmtbc wsbw ffe-bc
 all :
#
#climbc : 
#	@echo Test ClimBC, basic functionality 
#	-../../bin/FVSbcc < ClimBC.rsp
#	grep -v "\-999" ClimBC.sum      > ClimBC.tmp
#	grep -v "\-999" ClimBC.sum.save > ClimBC.tmp.save
#	-diff -w ClimBC.tmp ClimBC.tmp.save
#	rm ClimBC.tmp ClimBC.tmp.save
#	@echo Test ClimBC ended
#	
#mgmtbc : 
#	@echo "Test MgmtBC (with blanks in filenames)"
#	-../../bin/FVSbcc < "Mgmt BC.rsp"
#	grep -v "\-999" "Mgmt BC.sum"      > MgmtBC.tmp
#	grep -v "\-999" "Mgmt BC.sum.save" > MgmtBC.tmp.save
#	-diff -w MgmtBC.tmp MgmtBC.tmp.save
#	rm MgmtBC.tmp MgmtBC.tmp.save
#	@echo Test MgmtBC ended
#	
#wsbw : 
#	@echo "Test WSBW"
#	-../../bin/FVSbcc < WSBW-A.rsp
#	grep -v "\-999" WSBW-A.sum      > WSBW-A.tmp
#	grep -v "\-999" WSBW-A.sum.save > WSBW-A.tmp.save
#	-diff -w WSBW-A.tmp WSBW-A.tmp.save
#	rm WSBW-A.tmp WSBW-A.tmp.save
#	@echo Test WSBW ended
#
#ffe-bc : 
#	@echo "Test FFE-BC"
#	-../../bin/FVSbcc < FFE-BC.rsp
#	grep -v "\-999" FFE-BC.sum      > FFE-BC.tmp
#	grep -v "\-999" FFE-BC.sum.save > FFE-BC.tmp.save
#	-diff -w FFE-BC.tmp FFE-BC.tmp.save
#	rm FFE-BC.tmp FFE-BC.tmp.save fort.3
#	@echo Test FFE-BC ended



